/**
 * Tarım ve Orman Bakanlığı Destekleri
 * Son güncelleme: 2026-07 (2024-2026 Hayvancılık Desteklemeleri Kararı,
 * 2026 bitkisel üretim destekleri, KKYDP/IPARD III hibe programları esas
 * alınarak güncellendi).
 *
 * NOT: Destek tutarları/tarihleri yıllık kararnamelerle değişir. Bu liste
 * yılda 1-2 kez, ideal olarak her Ocak (hayvancılık) ve Mart (bitkisel)
 * ayı kararnameleri yayımlandığında elden geçirilmelidir.
 *
 * French (*Fr) translations were added on 2026-09-21, and Spanish (*Es)
 * translations on 2026-09-27, for every program. Both were written from the
 * Turkish/English text, not by a professional legal translator - have the
 * amounts and official terms reviewed before relying on them, and add the
 * *Fr and *Es fields to any new program you seed.
 */

export const supportProgramSeeds = [
  // ==================== BİTKİSEL ÜRETIM DESTEKLERİ ====================
  {
    title: "Bitkisel Üretim Temel Destekleme Ödemesi (Mazot-Gübre)",
    titleEn: "Basic Crop Production Support Payment (Fuel-Fertilizer)",
    titleFr: "Paiement de soutien de base à la production végétale (mazout-engrais)",
    titleEs: "Pago de Apoyo Básico a la Producción Vegetal (Gasóleo-Fertilizante)",
    description:
      "2026 üretim yılı için dekar başına 310 TL temel destek katsayısı uygulanır; ürün grubuna göre değişir (buğday/arpa 403 TL/da, ayçiçeği/soya/fındık/kanola 465 TL/da, pamuk/çeltik 1.395 TL/da). Çiftçi Kayıt Sistemi'ne kayıtlı olmak gerekir.",
    descriptionEn:
      "For the 2026 production year, a base support coefficient of 310 TL/decare applies, varying by crop group (wheat/barley 403 TL/da, sunflower/soy/hazelnut/canola 465 TL/da, cotton/rice 1,395 TL/da). Registration in the Farmer Registration System is required.",
    descriptionFr:
      "Pour l'année de production 2026, un coefficient de soutien de base de 310\u00a0TL par décare s'applique et varie selon le groupe de cultures (blé/orge 403\u00a0TL/da, tournesol/soja/noisette/colza 465\u00a0TL/da, coton/riz paddy 1\u00a0395\u00a0TL/da). L'inscription au Système d'enregistrement des agriculteurs (ÇKS) est obligatoire.",
    descriptionEs: "Para la campaña de producción de 2026 se aplica un coeficiente de apoyo básico de 310 TL por decárea, que varía según el grupo de cultivo (trigo/cebada 403 TL/da, girasol/soja/avellana/colza 465 TL/da, algodón/arroz cáscara 1.395 TL/da). Es obligatorio estar inscrito en el Sistema de Registro de Agricultores (ÇKS).",
    category: "bitkisel",
    subcategory: "mazot_gubre",
    amount: "310 TL/da temel + ürüne göre 403-1.395 TL/da arası",
    amountEn: "310 TL/decare base, 403-1,395 TL/decare depending on crop",
    amountFr: "310\u00a0TL/décare de base, puis 403 à 1\u00a0395\u00a0TL/décare selon la culture",
    amountEs: "310 TL/da de base, más entre 403 y 1.395 TL/da según el cultivo",
    eligibility: "ÇKS'ye kayıtlı tüm çiftçiler",
    eligibilityEn: "All farmers registered in the Farmer Registration System",
    eligibilityFr: "Tous les agriculteurs inscrits au Système d'enregistrement des agriculteurs (ÇKS)",
    eligibilityEs: "Todos los agricultores inscritos en el Sistema de Registro de Agricultores (ÇKS)",
    requiredDocs: "ÇKS belgesi, Banka hesap bilgileri, Kimlik fotokopisi",
    requiredDocsEn: "FRS certificate, Bank account details, ID copy",
    requiredDocsFr: "Attestation ÇKS, coordonnées bancaires, copie de la pièce d'identité",
    requiredDocsEs: "Certificado ÇKS, datos de la cuenta bancaria, fotocopia del documento de identidad",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    officialGazetteUrl:
      "https://www.resmigazete.gov.tr/arama?kelime=Bitkisel%20%C3%9Cretim%20Destekleme%20Karar%C4%B1%202026",
    status: "active",
    targetCrops: '["wheat", "corn", "sugar beet", "cotton", "sunflower", "rice", "soybean"]',
    priority: 100,
  },

  {
    title: "Tarım Arazilerinin Etkin Kullanımı Hibe Desteği",
    titleEn: "Agricultural Land Effective Use Grant Support",
    titleFr: "Subvention pour l'utilisation efficace des terres agricoles",
    titleEs: "Subvención para el Uso Eficaz de las Tierras Agrícolas",
    description:
      "İşlenmeyen veya nadasa bırakılan tarım arazilerinin yeniden üretime kazandırılmasına yönelik projelere yüzde 75'e kadar hibe desteği sağlanır. 2026'da Cumhurbaşkanlığı kararıyla yürürlüğe girmiştir.",
    descriptionEn:
      "Grant support of up to 75% for projects that bring unused or fallow agricultural land back into production. Enacted in 2026 by presidential decision.",
    descriptionFr:
      "Une subvention pouvant atteindre 75 % est accordée aux projets visant à remettre en production des terres agricoles inexploitées ou laissées en jachère. Entrée en vigueur en 2026 par décision présidentielle.",
    descriptionEs: "Se concede una subvención de hasta el 75 % para proyectos destinados a devolver a la producción tierras agrícolas no cultivadas o en barbecho. Entró en vigor en 2026 por decisión de la Presidencia.",
    category: "bitkisel",
    subcategory: "arazi_kullanim",
    amount: "Proje maliyetinin %75'ine kadar hibe",
    amountEn: "Up to 75% of project cost as a grant",
    amountFr: "Subvention pouvant atteindre 75 % du coût du projet",
    amountEs: "Subvención de hasta el 75 % del coste del proyecto",
    eligibility: "Nadasa bırakılan/işlenmeyen arazi sahibi çiftçiler ve üretici örgütleri",
    eligibilityEn: "Farmers and producer organizations owning fallow/unused land",
    eligibilityFr: "Agriculteurs et organisations de producteurs propriétaires de terres en jachère ou inexploitées",
    eligibilityEs: "Agricultores y organizaciones de productores propietarios de tierras en barbecho o sin cultivar",
    requiredDocs: "Proje dosyası, Arazi tapusu, ÇKS belgesi",
    requiredDocsEn: "Project file, Land deed, FRS certificate",
    requiredDocsFr: "Dossier de projet, titre de propriété du terrain, attestation ÇKS",
    requiredDocsEs: "Expediente del proyecto, escritura de la tierra, certificado ÇKS",
    applicationStart: new Date("2026-03-07"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    officialGazetteUrl:
      "https://www.resmigazete.gov.tr/arama?kelime=Tar%C4%B1m%20Arazilerinin%20Etkin%20Kullan%C4%B1m%C4%B1%20Hibe%20Deste%C4%9Fi",
    status: "active",
    priority: 98,
  },

  {
    title: "Sertifikalı Tohum Kullanım Desteği",
    titleEn: "Certified Seed Use Support",
    titleFr: "Aide à l'utilisation de semences certifiées",
    titleEs: "Apoyo al Uso de Semillas Certificadas",
    description: "Sertifikalı tohum kullanan çiftçilere kilogram başına destek verilir. Tohum alım faturası ibraz edilmelidir.",
    descriptionEn: "Support per kilogram for farmers using certified seeds. Seed purchase invoice must be presented.",
    descriptionFr: "Les agriculteurs qui utilisent des semences certifiées reçoivent une aide par kilogramme. La facture d'achat des semences doit être présentée.",
    descriptionEs: "Se concede apoyo por kilogramo a los agricultores que utilizan semillas certificadas. Debe presentarse la factura de compra de las semillas.",
    category: "bitkisel",
    subcategory: "tohum",
    amount: "Tohum türüne göre 5-15 TL/kg",
    amountEn: "5-15 TL/kg depending on seed type",
    amountFr: "5 à 15\u00a0TL/kg selon le type de semence",
    amountEs: "5-15 TL/kg según el tipo de semilla",
    eligibility: "Sertifikalı tohum kullanan ÇKS'li çiftçiler",
    eligibilityEn: "FRS-registered farmers using certified seeds",
    eligibilityFr: "Agriculteurs inscrits au ÇKS utilisant des semences certifiées",
    eligibilityEs: "Agricultores inscritos en el ÇKS que utilizan semillas certificadas",
    requiredDocs: "Tohum alım faturası, ÇKS belgesi, Tohum etiketi",
    requiredDocsEn: "Seed purchase invoice, FRS certificate, Seed label",
    requiredDocsFr: "Facture d'achat des semences, attestation ÇKS, étiquette des semences",
    requiredDocsEs: "Factura de compra de semillas, certificado ÇKS, etiqueta de la semilla",
    applicationStart: new Date("2026-01-15"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    targetCrops: '["wheat", "corn", "rice", "soybean"]',
    priority: 88,
  },

  {
    title: "Organik Tarım Desteği",
    titleEn: "Organic Farming Support",
    titleFr: "Aide à l'agriculture biologique",
    titleEs: "Apoyo a la Agricultura Ecológica",
    description: "Organik tarım yapan ve sertifikalı üreticilere alan bazlı destek sağlanır. Organik tarım sertifikası zorunludur.",
    descriptionEn: "Area-based support for certified organic farmers. Organic farming certificate is mandatory.",
    descriptionFr: "Une aide à la surface est accordée aux producteurs biologiques certifiés. Le certificat d'agriculture biologique est obligatoire.",
    descriptionEs: "Se proporciona apoyo por superficie a los productores ecológicos certificados. El certificado de agricultura ecológica es obligatorio.",
    category: "bitkisel",
    subcategory: "organik",
    amount: "300-600 TL/dekar (ürüne göre)",
    amountEn: "300-600 TL/decar (varies by crop)",
    amountFr: "300 à 600\u00a0TL/décare (selon la culture)",
    amountEs: "300-600 TL/decárea (según el cultivo)",
    eligibility: "Organik tarım sertifikası olan çiftçiler",
    eligibilityEn: "Farmers with organic farming certificate",
    eligibilityFr: "Agriculteurs titulaires d'un certificat d'agriculture biologique",
    eligibilityEs: "Agricultores con certificado de agricultura ecológica",
    requiredDocs: "Organik tarım sertifikası, ÇKS belgesi, Arazi tapusu",
    requiredDocsEn: "Organic certificate, FRS certificate, Land deed",
    requiredDocsFr: "Certificat d'agriculture biologique, attestation ÇKS, titre de propriété du terrain",
    requiredDocsEs: "Certificado de agricultura ecológica, certificado ÇKS, escritura de la tierra",
    applicationStart: new Date("2026-02-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    targetCrops: '["wheat", "tomato", "grape", "olive"]',
    priority: 85,
  },

  {
    title: "Kapalı Ortam Üretici ve Genç/Kadın Çiftçi İlave Desteği",
    titleEn: "Greenhouse Producer and Young/Woman Farmer Additional Support",
    titleFr: "Aide complémentaire pour les producteurs sous abri et les jeunes agriculteurs / agricultrices",
    titleEs: "Apoyo Adicional para Productores bajo Cubierta y Agricultores Jóvenes/Mujeres",
    description:
      "Kapalı ortamda (sera vb.) bitkisel üretim yapan kadın çiftçiler ile 41 yaşından küçük üreticilere temel desteğe ek ödeme yapılır.",
    descriptionEn:
      "Additional payment on top of the base support for women farmers and producers under age 41 doing greenhouse crop production.",
    descriptionFr:
      "Un paiement complémentaire s'ajoute au soutien de base pour les agricultrices et les producteurs de moins de 41 ans qui pratiquent la production végétale sous abri (serres, etc.).",
    descriptionEs: "Se realiza un pago adicional sobre el apoyo básico a las agricultoras y a los productores menores de 41 años que realizan producción vegetal bajo cubierta (invernaderos, etc.).",
    category: "bitkisel",
    subcategory: "genc_kadin_ilave",
    amount: "Temel destek katsayısına ilave ödeme (oran yıllık belirlenir)",
    amountEn: "Additional payment on top of the base coefficient (rate set annually)",
    amountFr: "Paiement complémentaire s'ajoutant au coefficient de base (taux fixé chaque année)",
    amountEs: "Pago adicional sobre el coeficiente de apoyo básico (el porcentaje se fija anualmente)",
    eligibility: "41 yaşından küçük üreticiler ve kadın çiftçiler, kapalı ortam üretimi yapanlar",
    eligibilityEn: "Producers under 41 and women farmers doing greenhouse production",
    eligibilityFr: "Producteurs de moins de 41 ans et agricultrices pratiquant la culture sous abri",
    eligibilityEs: "Productores menores de 41 años y agricultoras que realizan producción bajo cubierta",
    requiredDocs: "ÇKS belgesi, Kimlik, Sera/işletme kayıt belgesi",
    requiredDocsEn: "FRS certificate, ID, Greenhouse/business registration",
    requiredDocsFr: "Attestation ÇKS, pièce d'identité, justificatif d'enregistrement de la serre ou de l'exploitation",
    requiredDocsEs: "Certificado ÇKS, documento de identidad, certificado de registro del invernadero o de la explotación",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    priority: 75,
  },

  {
    title: "Toprak Analizi Desteği",
    titleEn: "Soil Analysis Support",
    titleFr: "Aide aux analyses de sol",
    titleEs: "Apoyo al Análisis de Suelos",
    description: "Çiftçilerin toprak analizi yaptırma masraflarının bir kısmı karşılanır. İl Tarım Müdürlükleri'nden yararlanılabilir.",
    descriptionEn: "Partial coverage of soil analysis costs for farmers. Available through Provincial Agricultural Directorates.",
    descriptionFr: "Une partie des frais d'analyse de sol des agriculteurs est prise en charge. Le service est accessible auprès des Directions provinciales de l'agriculture.",
    descriptionEs: "Se cubre una parte de los costes del análisis de suelo de los agricultores. Puede solicitarse en las Direcciones Provinciales de Agricultura.",
    category: "bitkisel",
    subcategory: "toprak",
    amount: "Ücretsiz veya %50 indirimli",
    amountEn: "Free or 50% discount",
    amountFr: "Gratuit ou avec 50 % de réduction",
    amountEs: "Gratuito o con un 50 % de descuento",
    eligibility: "Tüm çiftçiler",
    eligibilityEn: "All farmers",
    eligibilityFr: "Tous les agriculteurs",
    eligibilityEs: "Todos los agricultores",
    requiredDocs: "ÇKS belgesi, Arazi tapusu",
    requiredDocsEn: "FRS certificate, Land deed",
    requiredDocsFr: "Attestation ÇKS, titre de propriété du terrain",
    requiredDocsEs: "Certificado ÇKS, escritura de la tierra",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    priority: 60,
  },

  // ==================== HAYVANSAL ÜRETIM DESTEKLERİ ====================

  {
    title: "Büyükbaş Hayvancılık Temel Desteği (Buzağı/Malak)",
    titleEn: "Cattle Farming Basic Support (Calf/Buffalo Calf)",
    titleFr: "Aide de base à l'élevage bovin (veau / buffletin)",
    titleEs: "Apoyo Básico a la Ganadería Bovina (Ternero/Búfalo)",
    description:
      "2024-2026 Hayvancılık Desteklemeleri Kararı kapsamında buzağı başına 1.400 TL, malak başına 2.800 TL temel destek ödenir; ilave katsayılarla (soy kütüğü, suni tohumlama, aile işletmesi vb.) 10.000 TL'ye kadar çıkabilir. Genç ve kadın yetiştiricilere buzağı başına +980 TL ek ödeme yapılır.",
    descriptionEn:
      "Under the 2024-2026 Livestock Support Decision, 1,400 TL per calf and 2,800 TL per buffalo calf is paid as base support, rising up to 10,000 TL with additional coefficients (pedigree, artificial insemination, family farm, etc.). Young and women breeders get an extra 980 TL per calf.",
    descriptionFr:
      "Dans le cadre de la Décision 2024-2026 sur le soutien à l'élevage, un soutien de base de 1\u00a0400\u00a0TL par veau et de 2\u00a0800\u00a0TL par buffletin est versé ; avec les coefficients supplémentaires (pedigree, insémination artificielle, exploitation familiale, etc.), il peut atteindre 10\u00a0000\u00a0TL. Les jeunes éleveurs et les éleveuses reçoivent un complément de 980\u00a0TL par veau.",
    descriptionEs: "En el marco de la Decisión de Apoyos Ganaderos 2024-2026, se pagan 1.400 TL por ternero y 2.800 TL por ternero de búfala como apoyo básico; con coeficientes adicionales (pedigrí, inseminación artificial, explotación familiar, etc.) puede llegar hasta 10.000 TL. Los ganaderos jóvenes y las ganaderas reciben un pago adicional de 980 TL por ternero.",
    category: "hayvansal",
    subcategory: "buyukbas",
    amount: "Buzağı 1.400 TL, Malak 2.800 TL (+ katsayılarla 10.000 TL'ye kadar)",
    amountEn: "Calf 1,400 TL, Buffalo calf 2,800 TL (up to 10,000 TL with coefficients)",
    amountFr: "Veau 1\u00a0400\u00a0TL, buffletin 2\u00a0800\u00a0TL (jusqu'à 10\u00a0000\u00a0TL avec les coefficients)",
    amountEs: "Ternero 1.400 TL, ternero de búfala 2.800 TL (hasta 10.000 TL con los coeficientes)",
    eligibility: "Kayıtlı büyükbaş hayvan sahibi yetiştiriciler (TÜRKVET kaydı)",
    eligibilityEn: "Registered cattle owners (TÜRKVET registration)",
    eligibilityFr: "Éleveurs propriétaires de bovins enregistrés (enregistrement TÜRKVET)",
    eligibilityEs: "Ganaderos propietarios de bovinos registrados (registro TÜRKVET)",
    requiredDocs: "Hayvan kayıt belgesi (TÜRKVET), Küpe numarası, Banka hesabı",
    requiredDocsEn: "Animal registration (TÜRKVET), Ear tag number, Bank account",
    requiredDocsFr: "Certificat d'enregistrement de l'animal (TÜRKVET), numéro de boucle d'oreille, compte bancaire",
    requiredDocsEs: "Certificado de registro del animal (TÜRKVET), número de crotal, cuenta bancaria",
    applicationStart: new Date("2026-01-08"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/HAYGEM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    officialGazetteUrl:
      "https://www.resmigazete.gov.tr/arama?kelime=2024-2026%20Y%C4%B1llar%C4%B1nda%20Yap%C4%B1lacak%20Hayvanc%C4%B1l%C4%B1k%20Desteklemeleri",
    status: "active",
    targetLivestock: '["cow", "buffalo"]',
    priority: 95,
  },

  {
    title: "Küçükbaş Hayvancılık Temel Desteği",
    titleEn: "Small Ruminant Farming Basic Support",
    titleFr: "Aide de base à l'élevage de petits ruminants",
    titleEs: "Apoyo Básico a la Ganadería Ovina y Caprina",
    description:
      "Anaç koyun/keçiden doğan kuzu/oğlak başına temel destek ödemesi yapılır; aile işletmeleri ve örgütlü üreticilere ilave katsayı uygulanır.",
    descriptionEn:
      "Base support payment per lamb/kid born from registered ewes/does; additional coefficients apply for family farms and organized producers.",
    descriptionFr:
      "Un paiement de soutien de base est versé par agneau ou chevreau né de brebis ou chèvres reproductrices enregistrées ; des coefficients supplémentaires s'appliquent aux exploitations familiales et aux producteurs organisés.",
    descriptionEs: "Se realiza un pago de apoyo básico por cada cordero o cabrito nacido de ovejas o cabras reproductoras registradas; se aplican coeficientes adicionales para las explotaciones familiares y los productores organizados.",
    category: "hayvansal",
    subcategory: "kucukbas",
    amount: "Kuzu/oğlak başına ~300 TL temel destek (yıllık güncellenir)",
    amountEn: "~300 TL base support per lamb/kid (updated annually)",
    amountFr: "Environ 300\u00a0TL de soutien de base par agneau/chevreau (mis à jour chaque année)",
    amountEs: "~300 TL de apoyo básico por cordero/cabrito (se actualiza anualmente)",
    eligibility: "Kayıtlı küçükbaş hayvan sahibi yetiştiriciler (TÜRKVET kaydı)",
    eligibilityEn: "Registered sheep/goat owners (TÜRKVET registration)",
    eligibilityFr: "Éleveurs propriétaires d'ovins/caprins enregistrés (enregistrement TÜRKVET)",
    eligibilityEs: "Ganaderos propietarios de ovinos/caprinos registrados (registro TÜRKVET)",
    requiredDocs: "Hayvan kayıt belgesi (TÜRKVET), Küpe numarası, Banka hesabı",
    requiredDocsEn: "Animal registration (TÜRKVET), Ear tag number, Bank account",
    requiredDocsFr: "Certificat d'enregistrement de l'animal (TÜRKVET), numéro de boucle d'oreille, compte bancaire",
    requiredDocsEs: "Certificado de registro del animal (TÜRKVET), número de crotal, cuenta bancaria",
    applicationStart: new Date("2026-01-08"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/HAYGEM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    targetLivestock: '["sheep", "goat"]',
    priority: 90,
  },

  {
    title: "Arıcılık Yatırım Hibe Desteği (KKYDP)",
    titleEn: "Beekeeping Investment Grant Support (KKYDP)",
    titleFr: "Subvention à l'investissement apicole (KKYDP)",
    titleEs: "Subvención a la Inversión Apícola (KKYDP)",
    description:
      "Kırsal Kalkınma Yatırım Programı kapsamında arıcılık yatırımlarına (kovan, bal süzme makinesi, bal sağım çadırı, güneş enerjisi sistemi) yüzde 50-70 arası hibe desteği verilir; kadın girişimci, genç üretici ve birinci derece üretici örgütlerinde oran %70'e kadar çıkar.",
    descriptionEn:
      "Under the Rural Development Investment Program, 50-70% grant support is available for beekeeping investments (hives, honey extractors, harvesting tents, solar systems); the rate rises to 70% for women entrepreneurs, young producers, and first-level producer organizations.",
    descriptionFr:
      "Dans le cadre du Programme d'investissement pour le développement rural (KKYDP), une subvention de 50 à 70 % est accordée aux investissements apicoles (ruches, extracteurs de miel, tentes de récolte, systèmes solaires) ; le taux atteint 70 % pour les femmes entrepreneures, les jeunes producteurs et les organisations de producteurs de premier niveau.",
    descriptionEs: "En el marco del Programa de Inversión para el Desarrollo Rural, se concede una subvención de entre el 50 % y el 70 % para inversiones apícolas (colmenas, extractores de miel, tiendas de extracción, sistemas de energía solar); el porcentaje llega hasta el 70 % para mujeres emprendedoras, jóvenes productores y organizaciones de productores de primer grado.",
    category: "hayvansal",
    subcategory: "aricilik",
    amount: "Yatırım maliyetinin %50-70'i hibe",
    amountEn: "50-70% of investment cost as a grant",
    amountFr: "Subvention de 50 à 70 % du coût de l'investissement",
    amountEs: "Subvención del 50-70 % del coste de la inversión",
    eligibility: "Arıcı Kayıt Sistemi'ne kayıtlı arıcılar, KKYDP başvuru şartlarını taşıyanlar",
    eligibilityEn: "Beekeepers registered in the Beekeeper Registration System, meeting KKYDP requirements",
    eligibilityFr: "Apiculteurs inscrits au Système d'enregistrement des apiculteurs et remplissant les conditions du KKYDP",
    eligibilityEs: "Apicultores inscritos en el Sistema de Registro de Apicultores que cumplan los requisitos del KKYDP",
    requiredDocs: "Arıcı kayıt belgesi, Proje/yatırım dosyası, Kovan sayısı beyanı",
    requiredDocsEn: "Beekeeper registration, Project/investment file, Hive count declaration",
    requiredDocsFr: "Attestation d'enregistrement d'apiculteur, dossier de projet ou d'investissement, déclaration du nombre de ruches",
    requiredDocsEs: "Certificado de registro de apicultor, expediente del proyecto o inversión, declaración del número de colmenas",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/TRGM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    targetLivestock: '["bee"]',
    priority: 80,
  },

  {
    title: "Kanatlı Hayvancılık Desteği",
    titleEn: "Poultry Farming Support",
    titleFr: "Aide à l'aviculture",
    titleEs: "Apoyo a la Avicultura",
    description: "Yumurta ve et tavukçuluğu yapanlara kapasite bazlı destek sağlanır. Modern tesislere ek teşvik vardır.",
    descriptionEn: "Capacity-based support for egg and meat poultry farming. Additional incentives for modern facilities.",
    descriptionFr: "Une aide fondée sur la capacité est accordée aux éleveurs de poules pondeuses et de volailles de chair. Des incitations supplémentaires existent pour les installations modernes.",
    descriptionEs: "Se proporciona apoyo basado en la capacidad a quienes se dedican a la avicultura de puesta y de carne. Existen incentivos adicionales para las instalaciones modernas.",
    category: "hayvansal",
    subcategory: "kanatli",
    amount: "Değişken (kapasite bazlı)",
    amountEn: "Variable (capacity-based)",
    amountFr: "Variable (selon la capacité)",
    amountEs: "Variable (según la capacidad)",
    eligibility: "Kayıtlı kanatlı işletme sahipleri",
    eligibilityEn: "Registered poultry farm owners",
    eligibilityFr: "Propriétaires d'exploitations avicoles enregistrées",
    eligibilityEs: "Propietarios de explotaciones avícolas registradas",
    requiredDocs: "İşletme ruhsatı, Kapasite belgesi, ÇKS",
    requiredDocsEn: "Business license, Capacity certificate, FRS",
    requiredDocsFr: "Licence d'exploitation, certificat de capacité, ÇKS",
    requiredDocsEs: "Licencia de la explotación, certificado de capacidad, ÇKS",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    targetLivestock: '["chicken", "duck", "turkey"]',
    priority: 70,
  },

  // ==================== KIRSAL KALKINMA DESTEKLERİ ====================

  {
    title: "KKYDP Genç Girişimci Kırsal Kalkınma Hibesi",
    titleEn: "KKYDP Young Entrepreneur Rural Development Grant",
    titleFr: "Subvention KKYDP au développement rural pour les jeunes entrepreneurs",
    titleEs: "Subvención KKYDP al Desarrollo Rural para Jóvenes Emprendedores",
    description:
      "18-40 yaş arası genç girişimcilere yönelik geri ödemesiz kuruluş hibesi. Proje bütçesi KDV dahil 100.000-30.000.000 TL arasında olabilir; aile işletmeleri için üst limit 8.000.000 TL'dir. Arıcılık, hayvancılık ve bitkisel üretim projelerini kapsar.",
    descriptionEn:
      "Non-repayable startup grant for young entrepreneurs aged 18-40. Project budgets range from 100,000 to 30,000,000 TL including VAT; the cap for family businesses is 8,000,000 TL. Covers beekeeping, livestock, and crop production projects.",
    descriptionFr:
      "Subvention d'installation non remboursable destinée aux jeunes entrepreneurs de 18 à 40 ans. Le budget du projet peut aller de 100\u00a0000 à 30\u00a0000\u00a0000\u00a0TL, TVA incluse ; le plafond pour les exploitations familiales est de 8\u00a0000\u00a0000\u00a0TL. Couvre les projets d'apiculture, d'élevage et de production végétale.",
    descriptionEs: "Subvención de puesta en marcha, no reembolsable, para jóvenes emprendedores de entre 18 y 40 años. El presupuesto del proyecto puede oscilar entre 100.000 y 30.000.000 TL, IVA incluido; el límite para las explotaciones familiares es de 8.000.000 TL. Cubre proyectos de apicultura, ganadería y producción vegetal.",
    category: "kirsal_kalkinma",
    subcategory: "genc_ciftci",
    amount: "100.000-30.000.000 TL proje bütçesi (aile işletmesi üst limiti 8.000.000 TL), hibe",
    amountEn: "100,000-30,000,000 TL project budget (8,000,000 TL cap for family businesses), grant",
    amountFr: "Budget de projet de 100\u00a0000 à 30\u00a0000\u00a0000\u00a0TL (plafond de 8\u00a0000\u00a0000\u00a0TL pour les exploitations familiales), en subvention",
    amountEs: "Presupuesto de proyecto de 100.000-30.000.000 TL (límite de 8.000.000 TL para explotaciones familiares), a fondo perdido",
    eligibility: "18-40 yaş arası, kırsal alanda proje bazlı başvuran girişimciler",
    eligibilityEn: "Aged 18-40, entrepreneurs applying with a rural project",
    eligibilityFr: "Entrepreneurs de 18 à 40 ans déposant un projet en zone rurale",
    eligibilityEs: "Emprendedores de entre 18 y 40 años que presenten un proyecto en el medio rural",
    requiredDocs: "İş planı/proje dosyası, Diploma, Kimlik, ÇKS belgesi",
    requiredDocsEn: "Business plan/project file, Diploma, ID, FRS certificate",
    requiredDocsFr: "Plan d'affaires ou dossier de projet, diplôme, pièce d'identité, attestation ÇKS",
    requiredDocsEs: "Plan de negocio o expediente del proyecto, título académico, documento de identidad, certificado ÇKS",
    applicationStart: new Date("2026-01-15"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/TRGM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    priority: 92,
  },

  {
    title: "IPARD III Kırsal Kalkınma Hibesi",
    titleEn: "IPARD III Rural Development Grant",
    titleFr: "Subvention IPARD III au développement rural",
    titleEs: "Subvención IPARD III al Desarrollo Rural",
    description:
      "Avrupa Birliği fonlarından desteklenen kırsal kalkınma programı. 2026 yılında toplam 241 milyon Euro hibe desteği ayrılmıştır. Tarımsal işletmelerin modernizasyonu, işleme-pazarlama tesisleri ve kırsal ekonomik faaliyetlerin çeşitlendirilmesi desteklenir.",
    descriptionEn:
      "EU-funded rural development programme. A total of €241 million in grants is allocated for 2026. Supports modernization of agricultural holdings, processing-marketing facilities, and diversification of rural economic activities.",
    descriptionFr:
      "Programme de développement rural financé par l'Union européenne. Un total de 241 millions d'euros de subventions est alloué pour 2026. Il soutient la modernisation des exploitations agricoles, les installations de transformation et de commercialisation, ainsi que la diversification des activités économiques rurales.",
    descriptionEs: "Programa de desarrollo rural financiado con fondos de la Unión Europea. En 2026 se han asignado un total de 241 millones de euros en subvenciones. Apoya la modernización de las explotaciones agrícolas, las instalaciones de transformación y comercialización, y la diversificación de las actividades económicas rurales.",
    category: "kirsal_kalkinma",
    subcategory: "ipard",
    amount: "Proje bazlı hibe, AB fonlu (2026 toplam bütçe: 241 milyon Euro)",
    amountEn: "Project-based grant, EU-funded (2026 total budget: €241 million)",
    amountFr: "Subvention par projet, financée par l'UE (budget total 2026 : 241 millions d'euros)",
    amountEs: "Subvención por proyecto, financiada por la UE (presupuesto total 2026: 241 millones de euros)",
    eligibility: "IPARD kapsamındaki illerde tarımsal işletme ve kırsal ekonomik faaliyet sahipleri",
    eligibilityEn: "Owners of agricultural holdings and rural economic activities in IPARD-eligible provinces",
    eligibilityFr: "Propriétaires d'exploitations agricoles et d'activités économiques rurales dans les provinces éligibles à l'IPARD",
    eligibilityEs: "Propietarios de explotaciones agrícolas y actividades económicas rurales en las provincias incluidas en el IPARD",
    requiredDocs: "Proje başvuru dosyası, İşletme kayıt belgeleri, ÇKS/TÜRKVET kaydı",
    requiredDocsEn: "Project application file, Business registration documents, FRS/TÜRKVET registration",
    requiredDocsFr: "Dossier de candidature du projet, documents d'enregistrement de l'exploitation, enregistrement ÇKS/TÜRKVET",
    requiredDocsEs: "Expediente de solicitud del proyecto, documentos de registro de la explotación, registro ÇKS/TÜRKVET",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tkdk.gov.tr",
    provider: "Tarım ve Kırsal Kalkınmayı Destekleme Kurumu (TKDK)",
    providerEn: "Agriculture and Rural Development Support Institution (TKDK)",
    providerFr: "Institution de soutien à l'agriculture et au développement rural (TKDK)",
    providerEs: "Institución de Apoyo a la Agricultura y el Desarrollo Rural (TKDK)",
    status: "active",
    priority: 82,
  },

  {
    title: "Kadın Girişimci Desteği",
    titleEn: "Women Entrepreneur Support",
    titleFr: "Aide aux femmes entrepreneures",
    titleEs: "Apoyo a la Mujer Emprendedora",
    description: "Kırsal alanda kadın girişimcilere yönelik hibe ve eğitim desteği. Tarımsal faaliyetler ve işleme tesisleri için.",
    descriptionEn: "Grant and training support for women entrepreneurs in rural areas. For agricultural activities and processing facilities.",
    descriptionFr: "Subvention et soutien à la formation destinés aux femmes entrepreneures en milieu rural, pour des activités agricoles et des installations de transformation.",
    descriptionEs: "Subvención y apoyo formativo para mujeres emprendedoras en el medio rural, destinados a actividades agrícolas e instalaciones de transformación.",
    category: "kirsal_kalkinma",
    subcategory: "kadin_girisimci",
    amount: "30.000-200.000 TL",
    amountEn: "30,000-200,000 TL",
    amountFr: "30\u00a0000 à 200\u00a0000\u00a0TL",
    amountEs: "30.000-200.000 TL",
    eligibility: "Kırsal alanda yaşayan kadın girişimciler",
    eligibilityEn: "Women entrepreneurs living in rural areas",
    eligibilityFr: "Femmes entrepreneures vivant en milieu rural",
    eligibilityEs: "Mujeres emprendedoras que viven en el medio rural",
    requiredDocs: "Proje dosyası, Kimlik, İkametgah",
    requiredDocsEn: "Project file, ID, Residence certificate",
    requiredDocsFr: "Dossier de projet, pièce d'identité, justificatif de domicile",
    requiredDocsEs: "Expediente del proyecto, documento de identidad, certificado de empadronamiento",
    applicationStart: new Date("2026-02-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    providerEs: "Ministerio de Agricultura y Silvicultura",
    status: "active",
    priority: 78,
  },

  // ==================== KREDİ VE FİNANSMAN ====================

  {
    title: "Tarımsal Kredi Faiz Desteği",
    titleEn: "Agricultural Credit Interest Support",
    titleFr: "Aide aux intérêts des crédits agricoles",
    titleEs: "Apoyo a los Intereses del Crédito Agrícola",
    description: "Tarım Kredi Kooperatifi ve Ziraat Bankası'ndan alınan kredilerde faiz desteği sağlanır.",
    descriptionEn: "Interest support for loans obtained from Agricultural Credit Cooperatives and Ziraat Bank.",
    descriptionFr: "Une aide aux intérêts est accordée sur les prêts contractés auprès des Coopératives de crédit agricole et de Ziraat Bankası.",
    descriptionEs: "Se concede apoyo a los intereses de los préstamos obtenidos de las Cooperativas de Crédito Agrícola y de Ziraat Bankası.",
    category: "kredi",
    subcategory: "faiz_destegi",
    amount: "Faiz oranının %50-75'i",
    amountEn: "50-75% of interest rate",
    amountFr: "50 à 75 % du taux d'intérêt",
    amountEs: "50-75 % del tipo de interés",
    eligibility: "Kredili tarım yapan çiftçiler",
    eligibilityEn: "Farmers with agricultural loans",
    eligibilityFr: "Agriculteurs ayant un crédit agricole",
    eligibilityEs: "Agricultores con créditos agrícolas",
    requiredDocs: "Kredi sözleşmesi, ÇKS belgesi",
    requiredDocsEn: "Loan agreement, FRS certificate",
    requiredDocsFr: "Contrat de prêt, attestation ÇKS",
    requiredDocsEs: "Contrato de préstamo, certificado ÇKS",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.ziraatbank.com.tr",
    provider: "Ziraat Bankası ve Tarım Kredi Kooperatifleri",
    providerEn: "Ziraat Bank and Agricultural Credit Cooperatives",
    providerFr: "Ziraat Bankası et Coopératives de crédit agricole",
    providerEs: "Ziraat Bankası y las Cooperativas de Crédito Agrícola",
    status: "active",
    priority: 76,
  },

  // ==================== INTERNATIONAL PROGRAMS (added 2026-09-27 for the
  // CIHEAM Spain presentation) ====================
  //
  // Unlike the Turkish programs above, these describe the real national
  // implementation of the EU Common Agricultural Policy (France, Spain) and
  // Switzerland's direct-payments system, at the level of their well-known,
  // stable official mechanism names (e.g. "Écorégime"/"Ecorregímenes",
  // Swiss "Direktzahlungen"). Exact payment rates change every year by
  // national/EU decree and are described here only in general terms
  // (varies by zone/type, set annually) rather than a specific number -
  // verify current rates on the linked official site before quoting them
  // to anyone. All four languages (tr/en/fr/es) were machine-assisted
  // translations from scratch, not reviewed by a professional legal
  // translator or a native speaker in-country - same caveat as the *Fr/*Es
  // fields above.
  {
    title: "İsviçre Genel Doğrudan Ödemeler (Peyzaj ve Gıda Güvenliği Katkısı)",
    titleEn: "General Direct Payments (Cultural Landscape & Food Security Contributions)",
    titleFr: "Paiements directs généraux (contributions au paysage cultural et à la sécurité de l'approvisionnement)",
    titleEs: "Pagos Directos Generales (Contribuciones al Paisaje Cultivado y a la Seguridad del Abastecimiento)",
    description:
      "İsviçre Federal Tarım Ofisi (BLW/OFAG) tarafından yürütülen temel destek programı; ekolojik performans kanıtı (PER/ÖLN) şartını yerine getiren tüm çiftçilere hektar başına ödeme yapılır. Tutarlar bölgeye (ova/dağ) ve arazi tipine göre Federal Konsey tarafından yıllık belirlenir.",
    descriptionEn:
      "Switzerland's core support scheme, run by the Federal Office for Agriculture (FOAG/BLW/OFAG); farmers meeting the Proof of Ecological Performance (PER) requirement receive a per-hectare payment. Rates vary by zone (lowland/mountain) and land type and are set annually by the Federal Council.",
    descriptionFr:
      "Programme de soutien de base de la Suisse, géré par l'Office fédéral de l'agriculture (OFAG) ; les agriculteurs remplissant les prestations écologiques requises (PER) reçoivent un paiement par hectare. Les montants varient selon la zone (plaine/montagne) et le type de surface, et sont fixés chaque année par le Conseil fédéral.",
    descriptionEs:
      "Programa de apoyo básico de Suiza, gestionado por la Oficina Federal de Agricultura (OFAG/BLW); los agricultores que cumplen la prueba de rendimiento ecológico (PER) reciben un pago por hectárea. Los importes varían según la zona (llanura/montaña) y el tipo de superficie, y se fijan anualmente por el Consejo Federal.",
    category: "diger",
    subcategory: "genel_dogrudan_odeme",
    amount: "Bölge ve arazi tipine göre değişen hektar başına ödeme (oranlar yıllık belirlenir)",
    amountEn: "Per-hectare payment varying by zone and land type (rates set annually)",
    amountFr: "Paiement par hectare variable selon la zone et le type de surface (taux fixés chaque année)",
    amountEs: "Pago por hectárea variable según la zona y el tipo de superficie (tipos fijados anualmente)",
    eligibility: "Ekolojik Performans Kanıtı (PER/ÖLN) şartını sağlayan, İsviçre'de kayıtlı tarım işletmeleri",
    eligibilityEn: "Registered Swiss farms meeting the Proof of Ecological Performance (PER) requirement",
    eligibilityFr: "Exploitations agricoles suisses enregistrées remplissant les prestations écologiques requises (PER)",
    eligibilityEs: "Explotaciones agrícolas suizas registradas que cumplen la prueba de rendimiento ecológico (PER)",
    requiredDocs: "İşletme kayıt numarası, PER/ÖLN belgesi, arazi kullanım beyanı",
    requiredDocsEn: "Farm registration number, PER certificate, land-use declaration",
    requiredDocsFr: "Numéro d'exploitation, attestation PER, déclaration de surface",
    requiredDocsEs: "Número de explotación, certificado PER, declaración de superficies",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.blw.admin.ch",
    provider: "İsviçre Federal Tarım Ofisi (BLW/OFAG)",
    providerEn: "Federal Office for Agriculture (FOAG)",
    providerFr: "Office fédéral de l'agriculture (OFAG)",
    providerEs: "Oficina Federal de Agricultura (OFAG/BLW)",
    status: "active",
    country: "CH",
    priority: 100,
  },

  {
    title: "İsviçre Biyoçeşitlilik Katkısı (Ekolojik Öncelik Alanları)",
    titleEn: "Biodiversity Contributions (Ecological Priority Areas)",
    titleFr: "Contributions à la biodiversité (surfaces de promotion de la biodiversité)",
    titleEs: "Contribuciones a la Biodiversidad (Superficies de Fomento de la Biodiversidad)",
    description:
      "Çayır, çiçekli şerit, yüksek gövdeli meyve ağaçları gibi biyoçeşitlilik destekleme alanları ayıran çiftçilere ek ödeme yapılır. Kalite düzeyine (Q1/Q2) göre tutar artar.",
    descriptionEn:
      "Additional payment for farmers setting aside biodiversity-promoting areas (extensively used meadows, flower strips, high-stem fruit trees, etc.); the amount increases with quality level (Q1/Q2).",
    descriptionFr:
      "Paiement complémentaire pour les agriculteurs qui affectent des surfaces de promotion de la biodiversité (prairies extensives, bandes fleuries, arbres fruitiers à haute tige, etc.) ; le montant augmente avec le niveau de qualité (Q1/Q2).",
    descriptionEs:
      "Pago complementario para los agricultores que destinan superficies de fomento de la biodiversidad (prados extensivos, franjas floridas, árboles frutales de tronco alto, etc.); el importe aumenta según el nivel de calidad (Q1/Q2).",
    category: "diger",
    subcategory: "biyocesitlilik",
    amount: "Alan ve kalite düzeyine göre hektar başına ek ödeme",
    amountEn: "Additional per-hectare payment depending on area and quality level",
    amountFr: "Paiement complémentaire par hectare selon la surface et le niveau de qualité",
    amountEs: "Pago adicional por hectárea según la superficie y el nivel de calidad",
    eligibility: "Biyoçeşitlilik destekleme alanı ayıran, PER şartını sağlayan çiftçiler",
    eligibilityEn: "Farmers meeting the PER requirement who set aside biodiversity-promoting areas",
    eligibilityFr: "Agriculteurs remplissant les PER qui affectent des surfaces de promotion de la biodiversité",
    eligibilityEs: "Agricultores que cumplen el PER y destinan superficies de fomento de la biodiversidad",
    requiredDocs: "İşletme kayıt numarası, alan beyanı, kalite düzeyi kontrol raporu",
    requiredDocsEn: "Farm registration number, area declaration, quality-level inspection report",
    requiredDocsFr: "Numéro d'exploitation, déclaration de surface, rapport de contrôle du niveau de qualité",
    requiredDocsEs: "Número de explotación, declaración de superficie, informe de control del nivel de calidad",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.blw.admin.ch",
    provider: "İsviçre Federal Tarım Ofisi (BLW/OFAG)",
    providerEn: "Federal Office for Agriculture (FOAG)",
    providerFr: "Office fédéral de l'agriculture (OFAG)",
    providerEs: "Oficina Federal de Agricultura (OFAG/BLW)",
    status: "active",
    country: "CH",
    priority: 90,
  },

  {
    title: "İsviçre Organik Tarım Katkısı",
    titleEn: "Organic Farming Contribution",
    titleFr: "Contribution à l'agriculture biologique",
    titleEs: "Contribución a la Agricultura Ecológica",
    description:
      "Bio Suisse (Knospe) veya federal organik standardına göre sertifikalı üretim yapan işletmelere alan bazlı ek katkı ödenir.",
    descriptionEn:
      "Area-based additional contribution for holdings certified under the Bio Suisse (Knospe) label or the federal organic standard.",
    descriptionFr:
      "Contribution complémentaire à la surface pour les exploitations certifiées selon le label Bio Suisse (Bourgeon) ou la norme biologique fédérale.",
    descriptionEs:
      "Contribución adicional por superficie para las explotaciones certificadas con el sello Bio Suisse (Knospe) o la norma ecológica federal.",
    category: "bitkisel",
    subcategory: "organik",
    amount: "Arazi tipine göre değişen hektar başına katkı (yıllık belirlenir)",
    amountEn: "Per-hectare contribution varying by land type (set annually)",
    amountFr: "Contribution par hectare variable selon le type de surface (fixée chaque année)",
    amountEs: "Contribución por hectárea variable según el tipo de superficie (fijada anualmente)",
    eligibility: "Bio Suisse veya federal organik sertifikasına sahip çiftçiler",
    eligibilityEn: "Farmers holding Bio Suisse or federal organic certification",
    eligibilityFr: "Agriculteurs titulaires du label Bio Suisse ou de la certification biologique fédérale",
    eligibilityEs: "Agricultores con certificación Bio Suisse o ecológica federal",
    requiredDocs: "Organik sertifika, işletme kayıt numarası, alan beyanı",
    requiredDocsEn: "Organic certificate, farm registration number, area declaration",
    requiredDocsFr: "Certificat biologique, numéro d'exploitation, déclaration de surface",
    requiredDocsEs: "Certificado ecológico, número de explotación, declaración de superficie",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.blw.admin.ch",
    provider: "İsviçre Federal Tarım Ofisi (BLW/OFAG)",
    providerEn: "Federal Office for Agriculture (FOAG)",
    providerFr: "Office fédéral de l'agriculture (OFAG)",
    providerEs: "Oficina Federal de Agricultura (OFAG/BLW)",
    status: "active",
    country: "CH",
    priority: 80,
  },

  {
    title: "Fransa Sürdürülebilirlik için Temel Gelir Desteği (ABR)",
    titleEn: "Basic Income Support for Sustainability (ABR)",
    titleFr: "Aide de base au revenu pour la durabilité (ABR)",
    titleEs: "Ayuda Básica a la Renta para la Sostenibilidad (equivalente francés, ABR)",
    description:
      "AB Ortak Tarım Politikası (PAC) 2023-2027 çerçevesinde, aktif çiftçilere uygun hektar başına temel gelir desteği ödenir. FranceAgriMer/ASP tarafından yürütülür, yıllık tek başvuru (dossier PAC) ile talep edilir.",
    descriptionEn:
      "Under the EU Common Agricultural Policy (CAP) 2023-2027, a basic per-hectare income payment is made to active farmers on eligible land. Administered via FranceAgriMer/ASP and claimed through the annual single CAP application (dossier PAC).",
    descriptionFr:
      "Dans le cadre de la Politique agricole commune (PAC) 2023-2027, une aide de base au revenu est versée par hectare admissible aux agriculteurs actifs. Gérée par FranceAgriMer/l'ASP et demandée via le dossier PAC annuel unique.",
    descriptionEs:
      "En el marco de la Política Agrícola Común (PAC) 2023-2027 de la UE, se paga una ayuda básica a la renta por hectárea admisible a los agricultores activos. Gestionada por FranceAgriMer/la ASP y solicitada mediante la declaración PAC anual única.",
    category: "diger",
    subcategory: "gelir_destegi",
    amount: "Uygun hektar başına ödeme (ulusal referans birim değere göre, yıllık belirlenir)",
    amountEn: "Payment per eligible hectare (based on the national reference unit value, set annually)",
    amountFr: "Paiement par hectare admissible (selon la valeur unitaire de référence nationale, fixée chaque année)",
    amountEs: "Pago por hectárea admisible (según el valor unitario de referencia nacional, fijado anualmente)",
    eligibility: "PAC dosyası bulunan, aktif çiftçi statüsündeki tarım işletmeleri",
    eligibilityEn: "Farms with a CAP file (dossier PAC) held by an active farmer",
    eligibilityFr: "Exploitations disposant d'un dossier PAC et ayant le statut d'agriculteur actif",
    eligibilityEs: "Explotaciones con expediente PAC y con estatus de agricultor activo",
    requiredDocs: "PAC başvuru dosyası (TelePAC), arazi parsel beyanı (RPG), SIRET numarası",
    requiredDocsEn: "CAP application file (TelePAC), land parcel declaration (RPG), SIRET number",
    requiredDocsFr: "Dossier PAC (TelePAC), déclaration des parcelles (RPG), numéro SIRET",
    requiredDocsEs: "Expediente PAC (TelePAC), declaración de parcelas (RPG), número SIRET",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.franceagrimer.fr",
    provider: "Fransa Tarım ve Gıda Egemenliği Bakanlığı / FranceAgriMer",
    providerEn: "Ministry of Agriculture and Food Sovereignty / FranceAgriMer",
    providerFr: "Ministère de l'Agriculture et de la Souveraineté Alimentaire / FranceAgriMer",
    providerEs: "Ministerio de Agricultura y Soberanía Alimentaria / FranceAgriMer",
    status: "active",
    country: "FR",
    priority: 100,
  },

  {
    title: "Fransa Yeniden Dağıtıcı Tamamlayıcı Gelir Desteği (İlk Hektarlar)",
    titleEn: "Complementary Redistributive Income Support (First Hectares)",
    titleFr: "Paiement redistributif complémentaire au revenu (premiers hectares)",
    titleEs: "Ayuda Redistributiva Complementaria a la Renta (Primeras Hectáreas, Francia)",
    description:
      "Küçük ve orta ölçekli işletmeleri desteklemek için, bir işletmenin ilk belirli sayıdaki hektarına temel desteğe ek olarak yeniden dağıtıcı ödeme yapılır.",
    descriptionEn:
      "To support small and medium-sized farms, a redistributive payment is made on top of the basic support for a holding's first block of hectares.",
    descriptionFr:
      "Afin de soutenir les petites et moyennes exploitations, un paiement redistributif s'ajoute à l'aide de base pour les premiers hectares de l'exploitation.",
    descriptionEs:
      "Para apoyar a las explotaciones pequeñas y medianas, se abona un pago redistributivo adicional a la ayuda básica por las primeras hectáreas de la explotación.",
    category: "diger",
    subcategory: "yeniden_dagitim",
    amount: "İlk hektarlar için hektar başına ek ödeme (oran yıllık belirlenir)",
    amountEn: "Additional per-hectare payment on the first hectares (rate set annually)",
    amountFr: "Paiement complémentaire par hectare sur les premiers hectares (taux fixé chaque année)",
    amountEs: "Pago adicional por hectárea en las primeras hectáreas (tipo fijado anualmente)",
    eligibility: "Temel gelir desteğinden yararlanan tüm çiftçiler, özellikle küçük/orta ölçekli işletmeler",
    eligibilityEn: "All farmers receiving basic income support, particularly small/medium-sized holdings",
    eligibilityFr: "Tous les agriculteurs bénéficiant de l'aide de base au revenu, en particulier les petites et moyennes exploitations",
    eligibilityEs: "Todos los agricultores que reciben la ayuda básica a la renta, especialmente las explotaciones pequeñas y medianas",
    requiredDocs: "PAC başvuru dosyası (TelePAC), arazi parsel beyanı (RPG)",
    requiredDocsEn: "CAP application file (TelePAC), land parcel declaration (RPG)",
    requiredDocsFr: "Dossier PAC (TelePAC), déclaration des parcelles (RPG)",
    requiredDocsEs: "Expediente PAC (TelePAC), declaración de parcelas (RPG)",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.franceagrimer.fr",
    provider: "Fransa Tarım ve Gıda Egemenliği Bakanlığı / FranceAgriMer",
    providerEn: "Ministry of Agriculture and Food Sovereignty / FranceAgriMer",
    providerFr: "Ministère de l'Agriculture et de la Souveraineté Alimentaire / FranceAgriMer",
    providerEs: "Ministerio de Agricultura y Soberanía Alimentaria / FranceAgriMer",
    status: "active",
    country: "FR",
    priority: 90,
  },

  {
    title: "Fransa Eko-Rejim (Çevresel Uygulamalar İçin Ek Ödeme)",
    titleEn: "Eco-Scheme (Écorégime) - Environmental Practices Payment",
    titleFr: "Écorégime - paiement pour les pratiques environnementales",
    titleEs: "Ecorrégimen - Pago por Prácticas Medioambientales (Francia)",
    description:
      "Sertifikasyon (ör. HVE - Yüksek Çevresel Değer, organik tarım), ürün çeşitlendirme veya biyoçeşitlilik unsurları yoluyla çevre dostu uygulamaları benimseyen çiftçilere hektar başına ek ödeme yapılır.",
    descriptionEn:
      "Additional per-hectare payment for farmers adopting environmentally friendly practices, via certification (e.g. HVE - High Environmental Value, organic farming), crop diversification, or biodiversity features.",
    descriptionFr:
      "Paiement complémentaire par hectare pour les agriculteurs adoptant des pratiques respectueuses de l'environnement, via une certification (par ex. HVE - Haute Valeur Environnementale, agriculture biologique), la diversification des cultures ou des éléments favorables à la biodiversité.",
    descriptionEs:
      "Pago complementario por hectárea para los agricultores franceses que adoptan prácticas respetuosas con el medio ambiente, mediante certificación (p. ej. HVE - Alto Valor Medioambiental, agricultura ecológica), diversificación de cultivos o elementos de biodiversidad.",
    category: "diger",
    subcategory: "eko_rejim",
    amount: "Uygulama düzeyine göre değişen hektar başına ödeme (standart veya üst düzey)",
    amountEn: "Per-hectare payment varying by practice level (standard or higher tier)",
    amountFr: "Paiement par hectare variable selon le niveau de pratique (standard ou supérieur)",
    amountEs: "Pago por hectárea variable según el nivel de práctica (estándar o superior)",
    eligibility: "HVE/organik sertifikası olan veya çeşitlendirme-biyoçeşitlilik şartlarını sağlayan çiftçiler",
    eligibilityEn: "Farmers holding HVE/organic certification or meeting the diversification-biodiversity requirements",
    eligibilityFr: "Agriculteurs titulaires de la certification HVE/biologique ou remplissant les conditions de diversification-biodiversité",
    eligibilityEs: "Agricultores con certificación HVE/ecológica o que cumplen los requisitos de diversificación-biodiversidad",
    requiredDocs: "PAC başvuru dosyası, sertifikasyon belgesi (varsa), arazi parsel beyanı",
    requiredDocsEn: "CAP application file, certification document (if applicable), land parcel declaration",
    requiredDocsFr: "Dossier PAC, justificatif de certification (le cas échéant), déclaration des parcelles",
    requiredDocsEs: "Expediente PAC, justificante de certificación (si procede), declaración de parcelas",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.franceagrimer.fr",
    provider: "Fransa Tarım ve Gıda Egemenliği Bakanlığı / FranceAgriMer",
    providerEn: "Ministry of Agriculture and Food Sovereignty / FranceAgriMer",
    providerFr: "Ministère de l'Agriculture et de la Souveraineté Alimentaire / FranceAgriMer",
    providerEs: "Ministerio de Agricultura y Soberanía Alimentaria / FranceAgriMer",
    status: "active",
    country: "FR",
    priority: 80,
  },

  {
    title: "İspanya Sürdürülebilirlik için Temel Gelir Desteği (BISS)",
    titleEn: "Basic Income Support for Sustainability (BISS)",
    titleFr: "Aide de base au revenu pour la durabilité (équivalent espagnol, BISS)",
    titleEs: "Ayuda Básica a la Renta para la Sostenibilidad (BISS)",
    description:
      "AB Ortak Tarım Politikası (PAC) 2023-2027 kapsamında, uygun hektar başına temel gelir desteği ödenir. İspanya Tarım Garanti Fonu (FEGA) ve özerk bölge tarım daireleri tarafından, yıllık tek başvuru (Solicitud Única/PAC) ile yürütülür.",
    descriptionEn:
      "Under the EU Common Agricultural Policy (CAP) 2023-2027, a basic per-hectare income payment is made on eligible land. Run by the Spanish Agricultural Guarantee Fund (FEGA) and the regional agriculture departments, claimed through the annual single application (Solicitud Única/PAC).",
    descriptionFr:
      "Dans le cadre de la Politique agricole commune (PAC) 2023-2027, une aide de base au revenu est versée par hectare admissible. Gérée par le Fonds espagnol de garantie agraire (FEGA) et les administrations agricoles régionales, demandée via la demande unique annuelle (Solicitud Única/PAC).",
    descriptionEs:
      "En el marco de la Política Agrícola Común (PAC) 2023-2027, se paga una ayuda básica a la renta por hectárea admisible. Gestionada por el Fondo Español de Garantía Agraria (FEGA) y las consejerías de agricultura autonómicas, se solicita mediante la Solicitud Única/PAC anual.",
    category: "diger",
    subcategory: "gelir_destegi",
    amount: "Uygun hektar başına ödeme (bölgesel referans değere göre, yıllık belirlenir)",
    amountEn: "Payment per eligible hectare (based on the regional reference value, set annually)",
    amountFr: "Paiement par hectare admissible (selon la valeur de référence régionale, fixée chaque année)",
    amountEs: "Pago por hectárea admisible (según el valor de referencia regional, fijado anualmente)",
    eligibility: "Aktif çiftçi statüsünde olan, Solicitud Única/PAC başvurusu yapan tarım işletmeleri",
    eligibilityEn: "Farms with active-farmer status that submit the Solicitud Única/PAC application",
    eligibilityFr: "Exploitations ayant le statut d'agriculteur actif et déposant la demande Solicitud Única/PAC",
    eligibilityEs: "Explotaciones con estatus de agricultor activo que presentan la Solicitud Única/PAC",
    requiredDocs: "Solicitud Única/PAC başvuru dosyası, SIGPAC parsel referansı, işletme kayıt numarası",
    requiredDocsEn: "Solicitud Única/PAC application file, SIGPAC parcel reference, farm registration number",
    requiredDocsFr: "Dossier Solicitud Única/PAC, référence de parcelle SIGPAC, numéro d'exploitation",
    requiredDocsEs: "Expediente de Solicitud Única/PAC, referencia de parcela SIGPAC, número de explotación",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.mapa.gob.es",
    provider: "İspanya Tarım, Balıkçılık ve Gıda Bakanlığı (MAPA) / FEGA",
    providerEn: "Ministry of Agriculture, Fisheries and Food (MAPA) / FEGA",
    providerFr: "Ministère de l'Agriculture, de la Pêche et de l'Alimentation (MAPA) / FEGA",
    providerEs: "Ministerio de Agricultura, Pesca y Alimentación (MAPA) / FEGA",
    status: "active",
    country: "ES",
    priority: 100,
  },

  {
    title: "İspanya Yeniden Dağıtıcı Tamamlayıcı Gelir Desteği (İlk Hektarlar)",
    titleEn: "Complementary Redistributive Income Support (First Hectares)",
    titleFr: "Aide redistributive complémentaire au revenu (premiers hectares, Espagne)",
    titleEs: "Ayuda Redistributiva Complementaria a la Renta (Primeras Hectáreas)",
    description:
      "Küçük ve orta ölçekli işletmeleri desteklemek amacıyla, bir işletmenin ilk belirli sayıdaki hektarına temel desteğe ek olarak yeniden dağıtıcı ödeme yapılır.",
    descriptionEn:
      "To support small and medium-sized farms, a redistributive payment is made on top of the basic support for a holding's first block of hectares.",
    descriptionFr:
      "Afin de soutenir les petites et moyennes exploitations, un paiement redistributif s'ajoute à l'aide de base pour les premiers hectares de l'exploitation.",
    descriptionEs:
      "Para apoyar a las explotaciones pequeñas y medianas, se abona una ayuda redistributiva complementaria a la ayuda básica por las primeras hectáreas de la explotación.",
    category: "diger",
    subcategory: "yeniden_dagitim",
    amount: "İlk hektarlar için hektar başına ek ödeme (oran yıllık belirlenir)",
    amountEn: "Additional per-hectare payment on the first hectares (rate set annually)",
    amountFr: "Paiement complémentaire par hectare sur les premiers hectares (taux fixé chaque année)",
    amountEs: "Pago adicional por hectárea en las primeras hectáreas (importe fijado anualmente)",
    eligibility: "Temel gelir desteğinden yararlanan tüm çiftçiler, özellikle küçük/orta ölçekli işletmeler",
    eligibilityEn: "All farmers receiving basic income support, particularly small/medium-sized holdings",
    eligibilityFr: "Tous les agriculteurs bénéficiant de l'aide de base au revenu, en particulier les petites et moyennes exploitations",
    eligibilityEs: "Todos los agricultores que reciben la ayuda básica a la renta, especialmente las explotaciones pequeñas y medianas",
    requiredDocs: "Solicitud Única/PAC başvuru dosyası, SIGPAC parsel referansı",
    requiredDocsEn: "Solicitud Única/PAC application file, SIGPAC parcel reference",
    requiredDocsFr: "Dossier Solicitud Única/PAC, référence de parcelle SIGPAC",
    requiredDocsEs: "Expediente de Solicitud Única/PAC, referencia de parcela SIGPAC",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.mapa.gob.es",
    provider: "İspanya Tarım, Balıkçılık ve Gıda Bakanlığı (MAPA) / FEGA",
    providerEn: "Ministry of Agriculture, Fisheries and Food (MAPA) / FEGA",
    providerFr: "Ministère de l'Agriculture, de la Pêche et de l'Alimentation (MAPA) / FEGA",
    providerEs: "Ministerio de Agricultura, Pesca y Alimentación (MAPA) / FEGA",
    status: "active",
    country: "ES",
    priority: 90,
  },

  {
    title: "İspanya Eko-Rejimleri (Sürdürülebilir Uygulamalar İçin Ödeme)",
    titleEn: "Eco-Schemes (Ecorregímenes) - Sustainable Practices Payment",
    titleFr: "Écorégimes - paiement pour les pratiques durables (Espagne)",
    titleEs: "Ecorregímenes",
    description:
      "Ekstansif otlatma, münavebe/örtü bitkileri, biyoçeşitlilik alanları veya zeytinlik/bağ gibi kalıcı ürünlerde sürdürülebilir toprak yönetimi gibi uygulamaları benimseyen çiftçilere hektar başına ek ödeme yapılır.",
    descriptionEn:
      "Additional per-hectare payment for farmers adopting practices such as extensive grazing, crop rotation/cover crops, biodiversity spaces, or sustainable soil management on permanent crops like olive groves and vineyards.",
    descriptionFr:
      "Paiement complémentaire par hectare pour les agriculteurs adoptant des pratiques telles que le pâturage extensif, la rotation des cultures/cultures dérobées, les espaces de biodiversité, ou la gestion durable des sols sur cultures pérennes (oliveraies, vignobles).",
    descriptionEs:
      "Pago complementario por hectárea para los agricultores que adoptan prácticas como el pastoreo extensivo, la rotación de cultivos o cultivos de cubierta, los espacios de biodiversidad, o la gestión sostenible del suelo en cultivos permanentes como el olivar y el viñedo.",
    category: "diger",
    subcategory: "eko_rejim",
    amount: "Uygulanan eko-rejime göre değişen hektar başına ödeme",
    amountEn: "Per-hectare payment varying by the eco-scheme practice applied",
    amountFr: "Paiement par hectare variable selon l'écorégime appliqué",
    amountEs: "Pago por hectárea variable según el ecorregimen aplicado",
    eligibility: "En az bir eko-rejim uygulamasını yerine getiren, PAC başvurusu olan çiftçiler",
    eligibilityEn: "Farmers with a CAP application who implement at least one eco-scheme practice",
    eligibilityFr: "Agriculteurs disposant d'une demande PAC et mettant en œuvre au moins une pratique d'écorégime",
    eligibilityEs: "Agricultores con solicitud PAC que implementan al menos una práctica de ecorregimen",
    requiredDocs: "Solicitud Única/PAC başvuru dosyası, uygulama beyanı, SIGPAC parsel referansı",
    requiredDocsEn: "Solicitud Única/PAC application file, practice declaration, SIGPAC parcel reference",
    requiredDocsFr: "Dossier Solicitud Única/PAC, déclaration de pratique, référence de parcelle SIGPAC",
    requiredDocsEs: "Expediente de Solicitud Única/PAC, declaración de práctica, referencia de parcela SIGPAC",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.mapa.gob.es",
    provider: "İspanya Tarım, Balıkçılık ve Gıda Bakanlığı (MAPA) / FEGA",
    providerEn: "Ministry of Agriculture, Fisheries and Food (MAPA) / FEGA",
    providerFr: "Ministère de l'Agriculture, de la Pêche et de l'Alimentation (MAPA) / FEGA",
    providerEs: "Ministerio de Agricultura, Pesca y Alimentación (MAPA) / FEGA",
    status: "active",
    targetCrops: '["olive", "grape"]',
    country: "ES",
    priority: 80,
  },
];
