/**
 * Tarım ve Orman Bakanlığı Destekleri
 * Son güncelleme: 2026-07 (2024-2026 Hayvancılık Desteklemeleri Kararı,
 * 2026 bitkisel üretim destekleri, KKYDP/IPARD III hibe programları esas
 * alınarak güncellendi).
 *
 * NOT: Destek tutarları/tarihleri yıllık kararnamelerle değişir. Bu liste
 * yılda 1-2 kez, ideal olarak her Ocak (hayvancılık) ve Mart (bitkisel)
 * ayı kararnameleri yayımlandığında elden geçirilmelidir.
 *
 * French (*Fr) translations were added on 2026-09-21 for every program. They
 * were written from the Turkish/English text, not by a professional legal
 * translator - have the amounts and official terms reviewed before relying
 * on them, and add the *Fr fields to any new program you seed.
 */

export const supportProgramSeeds = [
  // ==================== BİTKİSEL ÜRETIM DESTEKLERİ ====================
  {
    title: "Bitkisel Üretim Temel Destekleme Ödemesi (Mazot-Gübre)",
    titleEn: "Basic Crop Production Support Payment (Fuel-Fertilizer)",
    titleFr: "Paiement de soutien de base à la production végétale (mazout-engrais)",
    description:
      "2026 üretim yılı için dekar başına 310 TL temel destek katsayısı uygulanır; ürün grubuna göre değişir (buğday/arpa 403 TL/da, ayçiçeği/soya/fındık/kanola 465 TL/da, pamuk/çeltik 1.395 TL/da). Çiftçi Kayıt Sistemi'ne kayıtlı olmak gerekir.",
    descriptionEn:
      "For the 2026 production year, a base support coefficient of 310 TL/decare applies, varying by crop group (wheat/barley 403 TL/da, sunflower/soy/hazelnut/canola 465 TL/da, cotton/rice 1,395 TL/da). Registration in the Farmer Registration System is required.",
    descriptionFr:
      "Pour l'année de production 2026, un coefficient de soutien de base de 310\u00a0TL par décare s'applique et varie selon le groupe de cultures (blé/orge 403\u00a0TL/da, tournesol/soja/noisette/colza 465\u00a0TL/da, coton/riz paddy 1\u00a0395\u00a0TL/da). L'inscription au Système d'enregistrement des agriculteurs (ÇKS) est obligatoire.",
    category: "bitkisel",
    subcategory: "mazot_gubre",
    amount: "310 TL/da temel + ürüne göre 403-1.395 TL/da arası",
    amountEn: "310 TL/decare base, 403-1,395 TL/decare depending on crop",
    amountFr: "310\u00a0TL/décare de base, puis 403 à 1\u00a0395\u00a0TL/décare selon la culture",
    eligibility: "ÇKS'ye kayıtlı tüm çiftçiler",
    eligibilityEn: "All farmers registered in the Farmer Registration System",
    eligibilityFr: "Tous les agriculteurs inscrits au Système d'enregistrement des agriculteurs (ÇKS)",
    requiredDocs: "ÇKS belgesi, Banka hesap bilgileri, Kimlik fotokopisi",
    requiredDocsEn: "FRS certificate, Bank account details, ID copy",
    requiredDocsFr: "Attestation ÇKS, coordonnées bancaires, copie de la pièce d'identité",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    officialGazetteUrl:
      "https://www.resmigazete.gov.tr/arama?kelime=Bitkisel%20%C3%9Cretim%20Destekleme%20Karar%C4%B1%202026",
    status: "active",
    targetCrops: '["wheat", "corn", "sugar beet", "cotton", "sunflower", "rice", "soybean"]',
    priority: 100,
  },

  {
    title: "Tarım Arazilerinin Etkin Kullanımı Hibe Desteği",
    titleEn: "Agricultural Land Effective Use Grant Support",
    titleFr: "Subvention pour l'utilisation efficace des terres agricoles",
    description:
      "İşlenmeyen veya nadasa bırakılan tarım arazilerinin yeniden üretime kazandırılmasına yönelik projelere yüzde 75'e kadar hibe desteği sağlanır. 2026'da Cumhurbaşkanlığı kararıyla yürürlüğe girmiştir.",
    descriptionEn:
      "Grant support of up to 75% for projects that bring unused or fallow agricultural land back into production. Enacted in 2026 by presidential decision.",
    descriptionFr:
      "Une subvention pouvant atteindre 75 % est accordée aux projets visant à remettre en production des terres agricoles inexploitées ou laissées en jachère. Entrée en vigueur en 2026 par décision présidentielle.",
    category: "bitkisel",
    subcategory: "arazi_kullanim",
    amount: "Proje maliyetinin %75'ine kadar hibe",
    amountEn: "Up to 75% of project cost as a grant",
    amountFr: "Subvention pouvant atteindre 75 % du coût du projet",
    eligibility: "Nadasa bırakılan/işlenmeyen arazi sahibi çiftçiler ve üretici örgütleri",
    eligibilityEn: "Farmers and producer organizations owning fallow/unused land",
    eligibilityFr: "Agriculteurs et organisations de producteurs propriétaires de terres en jachère ou inexploitées",
    requiredDocs: "Proje dosyası, Arazi tapusu, ÇKS belgesi",
    requiredDocsEn: "Project file, Land deed, FRS certificate",
    requiredDocsFr: "Dossier de projet, titre de propriété du terrain, attestation ÇKS",
    applicationStart: new Date("2026-03-07"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    officialGazetteUrl:
      "https://www.resmigazete.gov.tr/arama?kelime=Tar%C4%B1m%20Arazilerinin%20Etkin%20Kullan%C4%B1m%C4%B1%20Hibe%20Deste%C4%9Fi",
    status: "active",
    priority: 98,
  },

  {
    title: "Sertifikalı Tohum Kullanım Desteği",
    titleEn: "Certified Seed Use Support",
    titleFr: "Aide à l'utilisation de semences certifiées",
    description: "Sertifikalı tohum kullanan çiftçilere kilogram başına destek verilir. Tohum alım faturası ibraz edilmelidir.",
    descriptionEn: "Support per kilogram for farmers using certified seeds. Seed purchase invoice must be presented.",
    descriptionFr: "Les agriculteurs qui utilisent des semences certifiées reçoivent une aide par kilogramme. La facture d'achat des semences doit être présentée.",
    category: "bitkisel",
    subcategory: "tohum",
    amount: "Tohum türüne göre 5-15 TL/kg",
    amountEn: "5-15 TL/kg depending on seed type",
    amountFr: "5 à 15\u00a0TL/kg selon le type de semence",
    eligibility: "Sertifikalı tohum kullanan ÇKS'li çiftçiler",
    eligibilityEn: "FRS-registered farmers using certified seeds",
    eligibilityFr: "Agriculteurs inscrits au ÇKS utilisant des semences certifiées",
    requiredDocs: "Tohum alım faturası, ÇKS belgesi, Tohum etiketi",
    requiredDocsEn: "Seed purchase invoice, FRS certificate, Seed label",
    requiredDocsFr: "Facture d'achat des semences, attestation ÇKS, étiquette des semences",
    applicationStart: new Date("2026-01-15"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    targetCrops: '["wheat", "corn", "rice", "soybean"]',
    priority: 88,
  },

  {
    title: "Organik Tarım Desteği",
    titleEn: "Organic Farming Support",
    titleFr: "Aide à l'agriculture biologique",
    description: "Organik tarım yapan ve sertifikalı üreticilere alan bazlı destek sağlanır. Organik tarım sertifikası zorunludur.",
    descriptionEn: "Area-based support for certified organic farmers. Organic farming certificate is mandatory.",
    descriptionFr: "Une aide à la surface est accordée aux producteurs biologiques certifiés. Le certificat d'agriculture biologique est obligatoire.",
    category: "bitkisel",
    subcategory: "organik",
    amount: "300-600 TL/dekar (ürüne göre)",
    amountEn: "300-600 TL/decar (varies by crop)",
    amountFr: "300 à 600\u00a0TL/décare (selon la culture)",
    eligibility: "Organik tarım sertifikası olan çiftçiler",
    eligibilityEn: "Farmers with organic farming certificate",
    eligibilityFr: "Agriculteurs titulaires d'un certificat d'agriculture biologique",
    requiredDocs: "Organik tarım sertifikası, ÇKS belgesi, Arazi tapusu",
    requiredDocsEn: "Organic certificate, FRS certificate, Land deed",
    requiredDocsFr: "Certificat d'agriculture biologique, attestation ÇKS, titre de propriété du terrain",
    applicationStart: new Date("2026-02-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    targetCrops: '["wheat", "tomato", "grape", "olive"]',
    priority: 85,
  },

  {
    title: "Kapalı Ortam Üretici ve Genç/Kadın Çiftçi İlave Desteği",
    titleEn: "Greenhouse Producer and Young/Woman Farmer Additional Support",
    titleFr: "Aide complémentaire pour les producteurs sous abri et les jeunes agriculteurs / agricultrices",
    description:
      "Kapalı ortamda (sera vb.) bitkisel üretim yapan kadın çiftçiler ile 41 yaşından küçük üreticilere temel desteğe ek ödeme yapılır.",
    descriptionEn:
      "Additional payment on top of the base support for women farmers and producers under age 41 doing greenhouse crop production.",
    descriptionFr:
      "Un paiement complémentaire s'ajoute au soutien de base pour les agricultrices et les producteurs de moins de 41 ans qui pratiquent la production végétale sous abri (serres, etc.).",
    category: "bitkisel",
    subcategory: "genc_kadin_ilave",
    amount: "Temel destek katsayısına ilave ödeme (oran yıllık belirlenir)",
    amountEn: "Additional payment on top of the base coefficient (rate set annually)",
    amountFr: "Paiement complémentaire s'ajoutant au coefficient de base (taux fixé chaque année)",
    eligibility: "41 yaşından küçük üreticiler ve kadın çiftçiler, kapalı ortam üretimi yapanlar",
    eligibilityEn: "Producers under 41 and women farmers doing greenhouse production",
    eligibilityFr: "Producteurs de moins de 41 ans et agricultrices pratiquant la culture sous abri",
    requiredDocs: "ÇKS belgesi, Kimlik, Sera/işletme kayıt belgesi",
    requiredDocsEn: "FRS certificate, ID, Greenhouse/business registration",
    requiredDocsFr: "Attestation ÇKS, pièce d'identité, justificatif d'enregistrement de la serre ou de l'exploitation",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    priority: 75,
  },

  {
    title: "Toprak Analizi Desteği",
    titleEn: "Soil Analysis Support",
    titleFr: "Aide aux analyses de sol",
    description: "Çiftçilerin toprak analizi yaptırma masraflarının bir kısmı karşılanır. İl Tarım Müdürlükleri'nden yararlanılabilir.",
    descriptionEn: "Partial coverage of soil analysis costs for farmers. Available through Provincial Agricultural Directorates.",
    descriptionFr: "Une partie des frais d'analyse de sol des agriculteurs est prise en charge. Le service est accessible auprès des Directions provinciales de l'agriculture.",
    category: "bitkisel",
    subcategory: "toprak",
    amount: "Ücretsiz veya %50 indirimli",
    amountEn: "Free or 50% discount",
    amountFr: "Gratuit ou avec 50 % de réduction",
    eligibility: "Tüm çiftçiler",
    eligibilityEn: "All farmers",
    eligibilityFr: "Tous les agriculteurs",
    requiredDocs: "ÇKS belgesi, Arazi tapusu",
    requiredDocsEn: "FRS certificate, Land deed",
    requiredDocsFr: "Attestation ÇKS, titre de propriété du terrain",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    priority: 60,
  },

  // ==================== HAYVANSAL ÜRETIM DESTEKLERİ ====================

  {
    title: "Büyükbaş Hayvancılık Temel Desteği (Buzağı/Malak)",
    titleEn: "Cattle Farming Basic Support (Calf/Buffalo Calf)",
    titleFr: "Aide de base à l'élevage bovin (veau / buffletin)",
    description:
      "2024-2026 Hayvancılık Desteklemeleri Kararı kapsamında buzağı başına 1.400 TL, malak başına 2.800 TL temel destek ödenir; ilave katsayılarla (soy kütüğü, suni tohumlama, aile işletmesi vb.) 10.000 TL'ye kadar çıkabilir. Genç ve kadın yetiştiricilere buzağı başına +980 TL ek ödeme yapılır.",
    descriptionEn:
      "Under the 2024-2026 Livestock Support Decision, 1,400 TL per calf and 2,800 TL per buffalo calf is paid as base support, rising up to 10,000 TL with additional coefficients (pedigree, artificial insemination, family farm, etc.). Young and women breeders get an extra 980 TL per calf.",
    descriptionFr:
      "Dans le cadre de la Décision 2024-2026 sur le soutien à l'élevage, un soutien de base de 1\u00a0400\u00a0TL par veau et de 2\u00a0800\u00a0TL par buffletin est versé ; avec les coefficients supplémentaires (pedigree, insémination artificielle, exploitation familiale, etc.), il peut atteindre 10\u00a0000\u00a0TL. Les jeunes éleveurs et les éleveuses reçoivent un complément de 980\u00a0TL par veau.",
    category: "hayvansal",
    subcategory: "buyukbas",
    amount: "Buzağı 1.400 TL, Malak 2.800 TL (+ katsayılarla 10.000 TL'ye kadar)",
    amountEn: "Calf 1,400 TL, Buffalo calf 2,800 TL (up to 10,000 TL with coefficients)",
    amountFr: "Veau 1\u00a0400\u00a0TL, buffletin 2\u00a0800\u00a0TL (jusqu'à 10\u00a0000\u00a0TL avec les coefficients)",
    eligibility: "Kayıtlı büyükbaş hayvan sahibi yetiştiriciler (TÜRKVET kaydı)",
    eligibilityEn: "Registered cattle owners (TÜRKVET registration)",
    eligibilityFr: "Éleveurs propriétaires de bovins enregistrés (enregistrement TÜRKVET)",
    requiredDocs: "Hayvan kayıt belgesi (TÜRKVET), Küpe numarası, Banka hesabı",
    requiredDocsEn: "Animal registration (TÜRKVET), Ear tag number, Bank account",
    requiredDocsFr: "Certificat d'enregistrement de l'animal (TÜRKVET), numéro de boucle d'oreille, compte bancaire",
    applicationStart: new Date("2026-01-08"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/HAYGEM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    officialGazetteUrl:
      "https://www.resmigazete.gov.tr/arama?kelime=2024-2026%20Y%C4%B1llar%C4%B1nda%20Yap%C4%B1lacak%20Hayvanc%C4%B1l%C4%B1k%20Desteklemeleri",
    status: "active",
    targetLivestock: '["cow", "buffalo"]',
    priority: 95,
  },

  {
    title: "Küçükbaş Hayvancılık Temel Desteği",
    titleEn: "Small Ruminant Farming Basic Support",
    titleFr: "Aide de base à l'élevage de petits ruminants",
    description:
      "Anaç koyun/keçiden doğan kuzu/oğlak başına temel destek ödemesi yapılır; aile işletmeleri ve örgütlü üreticilere ilave katsayı uygulanır.",
    descriptionEn:
      "Base support payment per lamb/kid born from registered ewes/does; additional coefficients apply for family farms and organized producers.",
    descriptionFr:
      "Un paiement de soutien de base est versé par agneau ou chevreau né de brebis ou chèvres reproductrices enregistrées ; des coefficients supplémentaires s'appliquent aux exploitations familiales et aux producteurs organisés.",
    category: "hayvansal",
    subcategory: "kucukbas",
    amount: "Kuzu/oğlak başına ~300 TL temel destek (yıllık güncellenir)",
    amountEn: "~300 TL base support per lamb/kid (updated annually)",
    amountFr: "Environ 300\u00a0TL de soutien de base par agneau/chevreau (mis à jour chaque année)",
    eligibility: "Kayıtlı küçükbaş hayvan sahibi yetiştiriciler (TÜRKVET kaydı)",
    eligibilityEn: "Registered sheep/goat owners (TÜRKVET registration)",
    eligibilityFr: "Éleveurs propriétaires d'ovins/caprins enregistrés (enregistrement TÜRKVET)",
    requiredDocs: "Hayvan kayıt belgesi (TÜRKVET), Küpe numarası, Banka hesabı",
    requiredDocsEn: "Animal registration (TÜRKVET), Ear tag number, Bank account",
    requiredDocsFr: "Certificat d'enregistrement de l'animal (TÜRKVET), numéro de boucle d'oreille, compte bancaire",
    applicationStart: new Date("2026-01-08"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/HAYGEM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    targetLivestock: '["sheep", "goat"]',
    priority: 90,
  },

  {
    title: "Arıcılık Yatırım Hibe Desteği (KKYDP)",
    titleEn: "Beekeeping Investment Grant Support (KKYDP)",
    titleFr: "Subvention à l'investissement apicole (KKYDP)",
    description:
      "Kırsal Kalkınma Yatırım Programı kapsamında arıcılık yatırımlarına (kovan, bal süzme makinesi, bal sağım çadırı, güneş enerjisi sistemi) yüzde 50-70 arası hibe desteği verilir; kadın girişimci, genç üretici ve birinci derece üretici örgütlerinde oran %70'e kadar çıkar.",
    descriptionEn:
      "Under the Rural Development Investment Program, 50-70% grant support is available for beekeeping investments (hives, honey extractors, harvesting tents, solar systems); the rate rises to 70% for women entrepreneurs, young producers, and first-level producer organizations.",
    descriptionFr:
      "Dans le cadre du Programme d'investissement pour le développement rural (KKYDP), une subvention de 50 à 70 % est accordée aux investissements apicoles (ruches, extracteurs de miel, tentes de récolte, systèmes solaires) ; le taux atteint 70 % pour les femmes entrepreneures, les jeunes producteurs et les organisations de producteurs de premier niveau.",
    category: "hayvansal",
    subcategory: "aricilik",
    amount: "Yatırım maliyetinin %50-70'i hibe",
    amountEn: "50-70% of investment cost as a grant",
    amountFr: "Subvention de 50 à 70 % du coût de l'investissement",
    eligibility: "Arıcı Kayıt Sistemi'ne kayıtlı arıcılar, KKYDP başvuru şartlarını taşıyanlar",
    eligibilityEn: "Beekeepers registered in the Beekeeper Registration System, meeting KKYDP requirements",
    eligibilityFr: "Apiculteurs inscrits au Système d'enregistrement des apiculteurs et remplissant les conditions du KKYDP",
    requiredDocs: "Arıcı kayıt belgesi, Proje/yatırım dosyası, Kovan sayısı beyanı",
    requiredDocsEn: "Beekeeper registration, Project/investment file, Hive count declaration",
    requiredDocsFr: "Attestation d'enregistrement d'apiculteur, dossier de projet ou d'investissement, déclaration du nombre de ruches",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/TRGM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    targetLivestock: '["bee"]',
    priority: 80,
  },

  {
    title: "Kanatlı Hayvancılık Desteği",
    titleEn: "Poultry Farming Support",
    titleFr: "Aide à l'aviculture",
    description: "Yumurta ve et tavukçuluğu yapanlara kapasite bazlı destek sağlanır. Modern tesislere ek teşvik vardır.",
    descriptionEn: "Capacity-based support for egg and meat poultry farming. Additional incentives for modern facilities.",
    descriptionFr: "Une aide fondée sur la capacité est accordée aux éleveurs de poules pondeuses et de volailles de chair. Des incitations supplémentaires existent pour les installations modernes.",
    category: "hayvansal",
    subcategory: "kanatli",
    amount: "Değişken (kapasite bazlı)",
    amountEn: "Variable (capacity-based)",
    amountFr: "Variable (selon la capacité)",
    eligibility: "Kayıtlı kanatlı işletme sahipleri",
    eligibilityEn: "Registered poultry farm owners",
    eligibilityFr: "Propriétaires d'exploitations avicoles enregistrées",
    requiredDocs: "İşletme ruhsatı, Kapasite belgesi, ÇKS",
    requiredDocsEn: "Business license, Capacity certificate, FRS",
    requiredDocsFr: "Licence d'exploitation, certificat de capacité, ÇKS",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    targetLivestock: '["chicken", "duck", "turkey"]',
    priority: 70,
  },

  // ==================== KIRSAL KALKINMA DESTEKLERİ ====================

  {
    title: "KKYDP Genç Girişimci Kırsal Kalkınma Hibesi",
    titleEn: "KKYDP Young Entrepreneur Rural Development Grant",
    titleFr: "Subvention KKYDP au développement rural pour les jeunes entrepreneurs",
    description:
      "18-40 yaş arası genç girişimcilere yönelik geri ödemesiz kuruluş hibesi. Proje bütçesi KDV dahil 100.000-30.000.000 TL arasında olabilir; aile işletmeleri için üst limit 8.000.000 TL'dir. Arıcılık, hayvancılık ve bitkisel üretim projelerini kapsar.",
    descriptionEn:
      "Non-repayable startup grant for young entrepreneurs aged 18-40. Project budgets range from 100,000 to 30,000,000 TL including VAT; the cap for family businesses is 8,000,000 TL. Covers beekeeping, livestock, and crop production projects.",
    descriptionFr:
      "Subvention d'installation non remboursable destinée aux jeunes entrepreneurs de 18 à 40 ans. Le budget du projet peut aller de 100\u00a0000 à 30\u00a0000\u00a0000\u00a0TL, TVA incluse ; le plafond pour les exploitations familiales est de 8\u00a0000\u00a0000\u00a0TL. Couvre les projets d'apiculture, d'élevage et de production végétale.",
    category: "kirsal_kalkinma",
    subcategory: "genc_ciftci",
    amount: "100.000-30.000.000 TL proje bütçesi (aile işletmesi üst limiti 8.000.000 TL), hibe",
    amountEn: "100,000-30,000,000 TL project budget (8,000,000 TL cap for family businesses), grant",
    amountFr: "Budget de projet de 100\u00a0000 à 30\u00a0000\u00a0000\u00a0TL (plafond de 8\u00a0000\u00a0000\u00a0TL pour les exploitations familiales), en subvention",
    eligibility: "18-40 yaş arası, kırsal alanda proje bazlı başvuran girişimciler",
    eligibilityEn: "Aged 18-40, entrepreneurs applying with a rural project",
    eligibilityFr: "Entrepreneurs de 18 à 40 ans déposant un projet en zone rurale",
    requiredDocs: "İş planı/proje dosyası, Diploma, Kimlik, ÇKS belgesi",
    requiredDocsEn: "Business plan/project file, Diploma, ID, FRS certificate",
    requiredDocsFr: "Plan d'affaires ou dossier de projet, diplôme, pièce d'identité, attestation ÇKS",
    applicationStart: new Date("2026-01-15"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr/TRGM",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    priority: 92,
  },

  {
    title: "IPARD III Kırsal Kalkınma Hibesi",
    titleEn: "IPARD III Rural Development Grant",
    titleFr: "Subvention IPARD III au développement rural",
    description:
      "Avrupa Birliği fonlarından desteklenen kırsal kalkınma programı. 2026 yılında toplam 241 milyon Euro hibe desteği ayrılmıştır. Tarımsal işletmelerin modernizasyonu, işleme-pazarlama tesisleri ve kırsal ekonomik faaliyetlerin çeşitlendirilmesi desteklenir.",
    descriptionEn:
      "EU-funded rural development programme. A total of €241 million in grants is allocated for 2026. Supports modernization of agricultural holdings, processing-marketing facilities, and diversification of rural economic activities.",
    descriptionFr:
      "Programme de développement rural financé par l'Union européenne. Un total de 241 millions d'euros de subventions est alloué pour 2026. Il soutient la modernisation des exploitations agricoles, les installations de transformation et de commercialisation, ainsi que la diversification des activités économiques rurales.",
    category: "kirsal_kalkinma",
    subcategory: "ipard",
    amount: "Proje bazlı hibe, AB fonlu (2026 toplam bütçe: 241 milyon Euro)",
    amountEn: "Project-based grant, EU-funded (2026 total budget: €241 million)",
    amountFr: "Subvention par projet, financée par l'UE (budget total 2026 : 241 millions d'euros)",
    eligibility: "IPARD kapsamındaki illerde tarımsal işletme ve kırsal ekonomik faaliyet sahipleri",
    eligibilityEn: "Owners of agricultural holdings and rural economic activities in IPARD-eligible provinces",
    eligibilityFr: "Propriétaires d'exploitations agricoles et d'activités économiques rurales dans les provinces éligibles à l'IPARD",
    requiredDocs: "Proje başvuru dosyası, İşletme kayıt belgeleri, ÇKS/TÜRKVET kaydı",
    requiredDocsEn: "Project application file, Business registration documents, FRS/TÜRKVET registration",
    requiredDocsFr: "Dossier de candidature du projet, documents d'enregistrement de l'exploitation, enregistrement ÇKS/TÜRKVET",
    applicationStart: new Date("2026-01-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tkdk.gov.tr",
    provider: "Tarım ve Kırsal Kalkınmayı Destekleme Kurumu (TKDK)",
    providerEn: "Agriculture and Rural Development Support Institution (TKDK)",
    providerFr: "Institution de soutien à l'agriculture et au développement rural (TKDK)",
    status: "active",
    priority: 82,
  },

  {
    title: "Kadın Girişimci Desteği",
    titleEn: "Women Entrepreneur Support",
    titleFr: "Aide aux femmes entrepreneures",
    description: "Kırsal alanda kadın girişimcilere yönelik hibe ve eğitim desteği. Tarımsal faaliyetler ve işleme tesisleri için.",
    descriptionEn: "Grant and training support for women entrepreneurs in rural areas. For agricultural activities and processing facilities.",
    descriptionFr: "Subvention et soutien à la formation destinés aux femmes entrepreneures en milieu rural, pour des activités agricoles et des installations de transformation.",
    category: "kirsal_kalkinma",
    subcategory: "kadin_girisimci",
    amount: "30.000-200.000 TL",
    amountEn: "30,000-200,000 TL",
    amountFr: "30\u00a0000 à 200\u00a0000\u00a0TL",
    eligibility: "Kırsal alanda yaşayan kadın girişimciler",
    eligibilityEn: "Women entrepreneurs living in rural areas",
    eligibilityFr: "Femmes entrepreneures vivant en milieu rural",
    requiredDocs: "Proje dosyası, Kimlik, İkametgah",
    requiredDocsEn: "Project file, ID, Residence certificate",
    requiredDocsFr: "Dossier de projet, pièce d'identité, justificatif de domicile",
    applicationStart: new Date("2026-02-01"),
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.tarimorman.gov.tr",
    provider: "Tarım ve Orman Bakanlığı",
    providerEn: "Ministry of Agriculture and Forestry",
    providerFr: "Ministère de l'Agriculture et des Forêts",
    status: "active",
    priority: 78,
  },

  // ==================== KREDİ VE FİNANSMAN ====================

  {
    title: "Tarımsal Kredi Faiz Desteği",
    titleEn: "Agricultural Credit Interest Support",
    titleFr: "Aide aux intérêts des crédits agricoles",
    description: "Tarım Kredi Kooperatifi ve Ziraat Bankası'ndan alınan kredilerde faiz desteği sağlanır.",
    descriptionEn: "Interest support for loans obtained from Agricultural Credit Cooperatives and Ziraat Bank.",
    descriptionFr: "Une aide aux intérêts est accordée sur les prêts contractés auprès des Coopératives de crédit agricole et de Ziraat Bankası.",
    category: "kredi",
    subcategory: "faiz_destegi",
    amount: "Faiz oranının %50-75'i",
    amountEn: "50-75% of interest rate",
    amountFr: "50 à 75 % du taux d'intérêt",
    eligibility: "Kredili tarım yapan çiftçiler",
    eligibilityEn: "Farmers with agricultural loans",
    eligibilityFr: "Agriculteurs ayant un crédit agricole",
    requiredDocs: "Kredi sözleşmesi, ÇKS belgesi",
    requiredDocsEn: "Loan agreement, FRS certificate",
    requiredDocsFr: "Contrat de prêt, attestation ÇKS",
    applicationDeadline: new Date("2026-12-31"),
    link: "https://www.ziraatbank.com.tr",
    provider: "Ziraat Bankası ve Tarım Kredi Kooperatifleri",
    providerEn: "Ziraat Bank and Agricultural Credit Cooperatives",
    providerFr: "Ziraat Bankası et Coopératives de crédit agricole",
    status: "active",
    priority: 76,
  },
];
