/**
 * Tarım ve Orman Bakanlığı Destekleri - 2025
 * Manuel güncelleme: Yılda 1-2 kez kontrol edilmeli
 */

export const supportProgramSeeds = [
  // ==================== BİTKİSEL ÜRETIM DESTEKLERİ ====================
  {
    title: "Mazot ve Gübre Destekleme Ödemesi",
    titleEn: "Fuel and Fertilizer Support Payment",
    description: "Çiftçilere mazot ve gübre giderleri için hektar başına destek ödemesi yapılır. Çiftçi Kayıt Sistemi'ne kayıtlı olmak gerekir.",
    descriptionEn: "Support payment per hectare for fuel and fertilizer expenses to farmers. Registration in the Farmer Registration System is required.",
    category: "bitkisel",
    subcategory: "mazot_gubre",
    amount: "1.500 TL/dekar (değişken)",
    amountEn: "Variable based on crop type",
    eligibility: "ÇKS'ye kayıtlı tüm çiftçiler",
    eligibilityEn: "All farmers registered in FRS",
    requiredDocs: "ÇKS belgesi, Banka hesap bilgileri, Kimlik fotokopisi",
    requiredDocsEn: "FRS certificate, Bank account details, ID copy",
    applicationStart: new Date("2025-03-01"),
    applicationDeadline: new Date("2025-04-30"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetCrops: '["wheat", "corn", "sugar beet", "cotton", "sunflower"]',
    priority: 100,
  },

  {
    title: "Sertifikalı Tohum Kullanım Desteği",
    titleEn: "Certified Seed Use Support",
    description: "Sertifikalı tohum kullanan çiftçilere kilogram başına destek verilir. Tohum alım faturası ibraz edilmelidir.",
    descriptionEn: "Support per kilogram for farmers using certified seeds. Seed purchase invoice must be presented.",
    category: "bitkisel",
    subcategory: "tohum",
    amount: "Tohum türüne göre 5-15 TL/kg",
    amountEn: "5-15 TL/kg depending on seed type",
    eligibility: "Sertifikalı tohum kullanan ÇKS'li çiftçiler",
    eligibilityEn: "FRS-registered farmers using certified seeds",
    requiredDocs: "Tohum alım faturası, ÇKS belgesi, Tohum etiketi",
    requiredDocsEn: "Seed purchase invoice, FRS certificate, Seed label",
    applicationStart: new Date("2025-01-15"),
    applicationDeadline: new Date("2025-12-31"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetCrops: '["wheat", "corn", "rice", "soybean"]',
    priority: 90,
  },

  {
    title: "Organik Tarım Desteği",
    titleEn: "Organic Farming Support",
    description: "Organik tarım yapan ve sertifikalı üreticilere alan bazlı destek sağlanır. Organik tarım sertifikası zorunludur.",
    descriptionEn: "Area-based support for certified organic farmers. Organic farming certificate is mandatory.",
    category: "bitkisel",
    subcategory: "organik",
    amount: "300-600 TL/dekar (ürüne göre)",
    amountEn: "300-600 TL/decar (varies by crop)",
    eligibility: "Organik tarım sertifikası olan çiftçiler",
    eligibilityEn: "Farmers with organic farming certificate",
    requiredDocs: "Organik tarım sertifikası, ÇKS belgesi, Arazi tapusu",
    requiredDocsEn: "Organic certificate, FRS certificate, Land deed",
    applicationStart: new Date("2025-02-01"),
    applicationDeadline: new Date("2025-05-31"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetCrops: '["wheat", "tomato", "grape", "olive"]',
    priority: 85,
  },

  {
    title: "Toprak Analizi Desteği",
    titleEn: "Soil Analysis Support",
    description: "Çiftçilerin toprak analizi yaptırma masraflarının bir kısmı karşılanır. İl Tarım Müdürlükleri'nden yararlanılabilir.",
    descriptionEn: "Partial coverage of soil analysis costs for farmers. Available through Provincial Agricultural Directorates.",
    category: "bitkisel",
    subcategory: "toprak",
    amount: "Ücretsiz veya %50 indirimli",
    amountEn: "Free or 50% discount",
    eligibility: "Tüm çiftçiler",
    eligibilityEn: "All farmers",
    requiredDocs: "ÇKS belgesi, Arazi tapusu",
    requiredDocsEn: "FRS certificate, Land deed",
    applicationDeadline: new Date("2025-12-31"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    priority: 70,
  },

  // ==================== HAYVANSAL ÜRETIM DESTEKLERİ ====================

  {
    title: "Süt Primi Desteği",
    titleEn: "Milk Premium Support",
    description: "Süt üreticilerine litre başına prim ödemesi yapılır. Kayıt altına alınmış hayvanlardan elde edilen süt için geçerlidir.",
    descriptionEn: "Premium payment per liter for milk producers. Valid for milk obtained from registered animals.",
    category: "hayvansal",
    subcategory: "sut",
    amount: "0,50-1,00 TL/litre",
    amountEn: "0.50-1.00 TL/liter",
    eligibility: "Kayıtlı büyükbaş hayvan sahibi süt üreticileri",
    eligibilityEn: "Dairy farmers with registered cattle",
    requiredDocs: "Hayvan kayıt belgesi, Süt toplama fişleri, Banka hesabı",
    requiredDocsEn: "Animal registration, Milk collection slips, Bank account",
    applicationStart: new Date("2025-01-01"),
    applicationDeadline: new Date("2025-12-31"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetLivestock: '["cow", "buffalo", "goat", "sheep"]',
    priority: 95,
  },

  {
    title: "Damızlık Hayvan Desteği",
    titleEn: "Breeding Animal Support",
    description: "Yerli ırk damızlık hayvan alımında destek sağlanır. Soy kütüğü kayıtlı hayvanlar için geçerlidir.",
    descriptionEn: "Support for purchasing native breed breeding animals. Valid for pedigree registered animals.",
    category: "hayvansal",
    subcategory: "damizlik",
    amount: "5.000-20.000 TL/hayvan",
    amountEn: "5,000-20,000 TL/animal",
    eligibility: "ÇKS'li hayvancılık yapan çiftçiler",
    eligibilityEn: "FRS-registered livestock farmers",
    requiredDocs: "Damızlık belgesi, Alım faturası, Küpe numarası",
    requiredDocsEn: "Breeding certificate, Purchase invoice, Ear tag number",
    applicationStart: new Date("2025-02-15"),
    applicationDeadline: new Date("2025-11-30"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetLivestock: '["cow", "sheep", "goat"]',
    priority: 80,
  },

  {
    title: "Arıcılık Destekleme Programı",
    titleEn: "Beekeeping Support Program",
    description: "Arı kovanı başına destek ve arıcılık ekipmanları için teşvik verilir. Kayıtlı arıcılara yöneliktir.",
    descriptionEn: "Support per beehive and incentives for beekeeping equipment. For registered beekeepers.",
    category: "hayvansal",
    subcategory: "aricilik",
    amount: "150-300 TL/kovan",
    amountEn: "150-300 TL/hive",
    eligibility: "Arıcı Kayıt Sistemi'ne kayıtlı arıcılar",
    eligibilityEn: "Beekeepers registered in BRS",
    requiredDocs: "Arıcı kayıt belgesi, Kovan sayısı beyanı",
    requiredDocsEn: "Beekeeper registration, Hive count declaration",
    applicationStart: new Date("2025-03-01"),
    applicationDeadline: new Date("2025-06-30"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetLivestock: '["bee"]',
    priority: 75,
  },

  {
    title: "Kanatlı Hayvancılık Desteği",
    titleEn: "Poultry Farming Support",
    description: "Yumurta ve et tavukçuluğu yapanlara kapasite bazlı destek sağlanır. Modern tesislere ek teşvik vardır.",
    descriptionEn: "Capacity-based support for egg and meat poultry farming. Additional incentives for modern facilities.",
    category: "hayvansal",
    subcategory: "kanatli",
    amount: "Değişken (kapasite bazlı)",
    amountEn: "Variable (capacity-based)",
    eligibility: "Kayıtlı kanatlı işletme sahipleri",
    eligibilityEn: "Registered poultry farm owners",
    requiredDocs: "İşletme ruhsatı, Kapasite belgesi, ÇKS",
    requiredDocsEn: "Business license, Capacity certificate, FRS",
    applicationDeadline: new Date("2025-08-31"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    targetLivestock: '["chicken", "duck", "turkey"]',
    priority: 70,
  },

  // ==================== KIRSAL KALKINMA DESTEKLERİ ====================

  {
    title: "Genç Çiftçi Projesi",
    titleEn: "Young Farmer Project",
    description: "18-40 yaş arası genç çiftçilere hibe ve düşük faizli kredi desteği. İş planı hazırlanması gerekir.",
    descriptionEn: "Grant and low-interest loan support for young farmers aged 18-40. Business plan required.",
    category: "kirsal_kalkinma",
    subcategory: "genc_ciftci",
    amount: "50.000-500.000 TL (proje bazlı)",
    amountEn: "50,000-500,000 TL (project-based)",
    eligibility: "18-40 yaş arası, tarım/ziraat eğitimi alanlar öncelikli",
    eligibilityEn: "Age 18-40, priority for agricultural education",
    requiredDocs: "İş planı, Diploma, Kimlik, ÇKS belgesi",
    requiredDocsEn: "Business plan, Diploma, ID, FRS certificate",
    applicationStart: new Date("2025-01-15"),
    applicationDeadline: new Date("2025-03-31"),
    link: "https://www.tarimorman.gov.tr/TRGM",
    status: "active",
    priority: 90,
  },

  {
    title: "Kadın Girişimci Desteği",
    titleEn: "Women Entrepreneur Support",
    description: "Kırsal alanda kadın girişimcilere yönelik hibe ve eğitim desteği. Tarımsal faaliyetler ve işleme tesisleri için.",
    descriptionEn: "Grant and training support for women entrepreneurs in rural areas. For agricultural activities and processing facilities.",
    category: "kirsal_kalkinma",
    subcategory: "kadin_girisimci",
    amount: "30.000-200.000 TL",
    amountEn: "30,000-200,000 TL",
    eligibility: "Kırsal alanda yaşayan kadın girişimciler",
    eligibilityEn: "Women entrepreneurs living in rural areas",
    requiredDocs: "Proje dosyası, Kimlik, İkametgah",
    requiredDocsEn: "Project file, ID, Residence certificate",
    applicationStart: new Date("2025-02-01"),
    applicationDeadline: new Date("2025-04-30"),
    link: "https://www.tarimorman.gov.tr",
    status: "active",
    priority: 85,
  },

  // ==================== KREDİ VE FİNANSMAN ====================

  {
    title: "Tarımsal Kredi Faiz Desteği",
    titleEn: "Agricultural Credit Interest Support",
    description: "Tarım Kredi Kooperatifi ve Ziraat Bankası'ndan alınan kredilerde faiz desteği sağlanır.",
    descriptionEn: "Interest support for loans obtained from Agricultural Credit Cooperatives and Ziraat Bank.",
    category: "kredi",
    subcategory: "faiz_destegi",
    amount: "Faiz oranının %50-75'i",
    amountEn: "50-75% of interest rate",
    eligibility: "Kredili tarım yapan çiftçiler",
    eligibilityEn: "Farmers with agricultural loans",
    requiredDocs: "Kredi sözleşmesi, ÇKS belgesi",
    requiredDocsEn: "Loan agreement, FRS certificate",
    applicationDeadline: new Date("2025-12-31"),
    link: "https://www.ziraatbank.com.tr",
    status: "active",
    priority: 80,
  },
];
